### ISSUE TITLE
Anaconda Python issues

### ISSUE THREAD

**Issue by espenhgn** [LFPy/LFPy#115]
With Anaconda python (Ubuntu 18.04 LTS, Python 3 from conda, NEURON 7.6.2), LFPy scripts cannot be executed twice without resulting in hoc errors. Works fine with the system Python.

Probably not something we can fix yet given this thread: https://www.neuron.yale.edu/phpBB/viewtopic.php?f=2&t=3926
```
In [1]: run example1.py                                                         
running simulation...
done

In [2]: run example1.py                                                         
NEURON: dend1[1]  must connect from 0<=x<=1 of parent
 in j4a.hoc near line 214
 geometry()
           ^
        geometry()
      xopen("j4a.hoc")
    execute1("{xopen("j4...")
  load_file(1, "cells/cell...")
NEURON: lambda_f error: 0 diameter for 3d point 8 of dend1[2].
 in j4a.hoc near line 0
 ^
        execerror("lambda_f error:", "0 diameter...")
      lambda_f(100)
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
~/LFPy/examples/example1.py in <module>
     70 
     71 # Create cell
---> 72 cell = LFPy.Cell(**cell_parameters)
     73 # Align cell
     74 cell.set_rotation(x=4.99, y=-4.33, z=3.14)

~/.local/lib/python3.6/site-packages/LFPy-2.0.0-py3.6-linux-x86_64.egg/LFPy/cell.py in __init__(self, morphology, v_init, Ra, cm, passive, passive_parameters, extracellular, tstart, tstop, dt, nsegs_method, lambda_f, d_lambda, max_nsegs_length, delete_sections, custom_code, custom_fun, custom_fun_args, pt3d, celsius, verbose, **kwargs)
    275 
    276         #set number of segments accd to rule, and calculate the number
--> 277         self._set_nsegs(nsegs_method, lambda_f, d_lambda, max_nsegs_length)
    278         self.totnsegs = self._calc_totnsegs()
    279         if self.verbose:

~/.local/lib/python3.6/site-packages/LFPy-2.0.0-py3.6-linux-x86_64.egg/LFPy/cell.py in _set_nsegs(self, nsegs_method, lambda_f, d_lambda, max_nsegs_length)
    399             self._set_nsegs_lambda100(d_lambda)
    400         elif nsegs_method == 'lambda_f':
--> 401             self._set_nsegs_lambda_f(lambda_f, d_lambda)
    402         elif nsegs_method == 'fixed_length':
    403             self._set_nsegs_fixed_length(max_nsegs_length)

~/.local/lib/python3.6/site-packages/LFPy-2.0.0-py3.6-linux-x86_64.egg/LFPy/cell.py in _set_nsegs_lambda_f(self, frequency, d_lambda)
    500         for sec in self.allseclist:
    501             sec.nseg = int((sec.L / (d_lambda*neuron.h.lambda_f(frequency,
--> 502                                                 sec=sec)) + .9) / 2)*2 + 1
    503         if self.verbose:
    504             print("set nsegs using lambda-rule with frequency %i." % frequency)

RuntimeError: hoc error
```

**Comment by torbjone** [comment]
This looks very much like an error I have had for a long time, where I can not make new cell models after a matplotlib Figure has been made. I have not found any solution, other than not plotting anything before all simulations are done.

**Comment by espenhgn** [comment]
@torbjone, ok maybe it's unrelated then. In that forum thread matplotlib is not used.

**Comment by espenhgn** [comment]
Closing (for now), as it appears to be an issue with Neuron and not LFPy.

**Comment by steinnhauser** [comment]
Is there any proposed solution/workaround for this issue? Despite it being a Neuron bug? Thanks!

**Comment by espenhgn** [comment]
Hi @steinnhauser; Do you currently encounter this issue? I see in the original post that this was with  NEURON 7.6.2, but we don't support NEURON that old anymore. NEURON >= 7.6.4 only. The current versions of both NEURON and LFPy on the conda-forge is up to date, so perhaps perform an update.

**Comment by steinnhauser** [comment]
Found the cause of it now. Strange bug, so might be the way the modules are set up on my computer. If I import in the following order:
```
from LFPy import NetworkCell, Network, Synapse, RecExtElectrode
import mpi4py as MPI
```
then a hoc error is generated. But importing the MPI modules first
```
import mpi4py as MPI
from LFPy import NetworkCell, Network, Synapse, RecExtElectrode
```
solves the issue. Seems it's best for the LFPy modules to be imported last of all.

**Comment by espenhgn** [comment]
Hi @steinnhauser; importing MPI before LFPy/neuron is not really a general fix even if may it solve your particular problem. We are sometimes using LFPy without NEURON being aware of any MPI environment (in hybridLFPy for example). If you are indeed seeing problems with the **current** versions of LFPy/NEURON, please provide the error messages, a minimal reproducer, as well as the output of `conda list` and `conda info`.
