### ISSUE TITLE
LFPy.Network simulation ignores first synapse

### ISSUE THREAD

**Issue by torbjone** [LFPy/LFPy#117]
I have a problem with LFPy's Network functionality. It appears that when inserting synapses by LFPy.Synapse, the first inserted synapse is mysteriously forgotten by LFPy/NEURON. 

In the dummy example bellow (which should be placed in the "example_network" folder), I insert two synapses, and both are included if the simulation is run with TemplateCell and cell.simulate(). However, if instead the cell model is initiated with LFPy.Network and the simulation run with network.simulate(), the first synapse (no matter how many you use) is forgotten.

**Comment by torbjone** [comment]
[example_network_stripped.txt](https://github.com/LFPy/LFPy/files/2812795/example_network_stripped.txt)

**Comment by espenhgn** [comment]
Tx, will take a look.

**Comment by espenhgn** [comment]
@torbjone, which exact versions of NEURON, LFPy and Python do you use?

**Comment by torbjone** [comment]
NEURON7.5 and Python 3.6.3 and LFPy 2.0.0
Do you not get the same problem on your end? I can test at home with the newest NEURON version.

**Comment by espenhgn** [comment]
Seems broken also here. I'd look for differences in how the network.simulate method instantiates NetCon events vs. the corresponding Cell.simulate method.

**Comment by espenhgn** [comment]
Btw., I'm on LFPy@master, NEURON 7.7.0-5-g0905f228, Python 3.7.2 - however my build appears to be crippled and may downgrade again to Python 3.6

**Comment by espenhgn** [comment]
PR #119 should fix the issue. Will close this ticket as soon as I merge the PR.
