### ISSUE TITLE
obsoletes requirements

### ISSUE THREAD

**Issue by lbazan** [LFPy/LFPy#128]
Hi LFPy team --

Can you update the requirements...

Cheers,

**Comment by lbazan** [comment]
/usr/lib64/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^~~~~~~

**Comment by espenhgn** [comment]
Hi @lbazan. As far as I know these warnings occur during compilation  whenever numpy is used with Cython (that is, while installing LFPy some .pyx files are translated to C and compiled), are completely normal, and has nothing to do with LFPy per se. 

Therefore closing this issue.
