### ISSUE TITLE
mpi4py 3.0.1

### ISSUE THREAD

**Issue by lbazan** [LFPy/LFPy#139]
running test
Searching for mpi4py>=1.2
Reading https://pypi.org/simple/mpi4py/
Downloading https://files.pythonhosted.org/packages/55/a2/c827b196070e161357b49287fa46d69f25641930fd5f854722319d431843/mpi4py-3.0.1.tar.gz#sha256=6549a5b81931303baf6600fa2e3bc04d8bd1d5c82f3c21379d0d64a9abcca851
Best match: mpi4py 3.0.1
Processing mpi4py-3.0.1.tar.gz
Writing /tmp/easy_install-fqume4gh/mpi4py-3.0.1/setup.cfg
Running mpi4py-3.0.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-fqume4gh/mpi4py-3.0.1/egg-dist-tmp-tj4508jy
/usr/bin/ld: cannot find -llmpe
collect2: error: ld returned 1 exit status
/usr/bin/ld: cannot find -lvt-mpi
collect2: error: ld returned 1 exit status
/usr/bin/ld: cannot find -lvt.mpi
collect2: error: ld returned 1 exit status
/usr/bin/ld: cannot find -lvt-mpi
collect2: error: ld returned 1 exit status
/usr/bin/ld: cannot find -lvt.mpi
collect2: error: ld returned 1 exit status
/usr/bin/ld: cannot find -lvt-hyb
collect2: error: ld returned 1 exit status
/usr/bin/ld: cannot find -lvt.ompi
collect2: error: ld returned 1 exit status
_configtest.c:2:10: fatal error: mpi.h: No such file or directory
    2 | #include <mpi.h>
      |          ^~~~~~~
compilation terminated.

**Comment by espenhgn** [comment]
Hi. This seems to be due to a lack of MPI libraries on your machine, and may not have anything to do with LFPy per se. Not sure what OS/python etc. you are using, but try and install LFPy dependencies using your standard package provider, issuing e.g., `sudo apt install python3-mpi4py` or `conda install mpi4py`

**Comment by espenhgn** [comment]
Closing as this issue is not likely related to LFPy.
