### ISSUE TITLE
Code reformatting

### ISSUE THREAD

**Issue by espenhgn** [LFPy/LFPy#14]
Keyword arguments to different classes and methods should be changed for clarity.

- [x] `Cell` keyword arguments `tstartms` & `tstopms` to `tstart` and `tstop`.

- [x] `RecExtElectrode` parameter `method="som_as_point"` to `"soma_as_point"`.

- [x] Make method `"soma_as_point"` default.

- [x] if method `"soma_as_point"` is used and there is no soma, what do we do?

- [x] Make `passive=default` default.

- [x] `Cell.set_pos(xpos=0, ypos=0, zpos=0)` to `Cell.set_pos(x=0, y=0, z=0)`.

- [x] `inputgenerators` module, do we even want to support these functions? Difficult to test if random output is truly following the different statistical distributions. We could rather create one function drawing interspike intervals from any scipy.stats continuous distribution

- [x] `Synapse/StimIntElectrode` `record_current` parameters. Both these and `Cell.simulate` parameters `rec_isyn/rec_istim` has to be True. One should suffice 

- [x] `class PointProcessPlayInSoma` nonfunctional codes removed (in PR #32)

- [x] `class Cell` should accept a (filled) `neuron.h.SectionList` object instead of reading in all sections from the neuron namespace (using `neuron.h.allsec()`) when parameter `morphology = None`.  

- [x] Writing output files while network simulations are running

- [x] Connection-set algebra

**Comment by torbjone** [comment]
I suggest also (i) changing to "soma_as_point" to default since this is what we usually use, and (ii) changing to "passive": False as default, since I find it a bit strange to by default set a specific set of parameters. I know of at least tree people, including myself, that has at some point spent time debugging the code, only to find out that this was the problem.

**Comment by espenhgn** [comment]
@torbjone Agree with all points. NEURON by default also do not set any parameters except cm and Ra, along with implausible geometry features. Updated list above

**Comment by espenhgn** [comment]
PR #35 fixes a number of bullets above. For method `soma_as_point`, a warning is raised somewhere else if there is infact no soma section (`Cell.somav` attribute not set).

**Comment by espenhgn** [comment]
Removed the points 

- [ ] Run simulations up to `tstop` but not including (such that # timesteps is an even number)

- [ ] Remove h5py as a dependency (cf. #100), use exdir or something

as v2 is now "final". I'd consider these two issues for a future target version as part of a larger effort to produce a consistent output format, structured accd to NWB and saved on exdir format, or something along those lines. 

Closing issue for now.
