### ISSUE TITLE
Run LFPy examples on myBinder.org

### ISSUE THREAD

**Issue by torbjone** [LFPy/LFPy#143]
I have been able to run LFPy 2.0 on MyBinder.org, by just having an "environment.yml" file in the repository with this content:

name: lfpy
channels:
  - conda-forge
dependencies:
  - python=3
  - numpy
  - scipy
  - matplotlib
  - Cython
  - h5py
  - gxx_linux-64
  - neuron=*=mpi_*
  - nest-simulator=*=mpi_openmpi*
  - pytest
  - pip
  - pip:
    - LFPy==2.0.0

----
This is very convenient for demonstrations, tutorial etc, since users can try LFPy without any installation.

I was considering making a repository that just contained the LFPy examples and linking to it from the LFPy github page, but an alternative would be to just add the environment file directly into LFPy, like I have done on a fork which now seems to work on mybinder:

https://mybinder.org/v2/gh/torbjone/LFPy/binder_test

Any objections to just add this environment file to LFPy? Would it destroy Travis, or anything like that?

**Comment by espenhgn** [comment]
Hi @torbjone. Having some LFPy examples on Mybinder.org would be great I agree. 

But shouldn't the existing ubuntu conda-env file (https://github.com/LFPy/LFPy/blob/master/conda_environment_ubuntu.yml) already work? It doesn't include pip or pip install LFPy and will only install required LFPy dependencies though. LFPy itself is on conda-forge (via its feedstock here: https://github.com/conda-forge/lfpy-feedstock) there should not be a need to pip install it. 

Including NEST in your list of dependencies is a mistake I think ;-)

**Comment by torbjone** [comment]
Yes, I think the current file should work, but it would have to be renamed to "environment.yml" I think. Is that OK? 

NEST was only there because the environment file was originally meant for a course that used NEST as well, and could of course be removed.

**Comment by espenhgn** [comment]
Forgot to add: TravisCI shouldn't be affected. 

I think naming the file conda_environment_binder.yml (or similar) if possible would be preferable as to not cause confusion (environment.yml is ambiguous with several env files). Shouldn't it be possible on mybinder.org to specify which env file to use? People shouldn't try to use it on Windows or macos (because of gxx_linux-64).

**Comment by espenhgn** [comment]
Hmm, maybe we can have an environment.yml file like:
```
name: lfpy
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3
  - lfpy
  - <additional requirements for examples>
```

**Comment by torbjone** [comment]
Without 'gxx_linux-64' I get an error when running 'nrnivmodl':

/src/conda/neuron-7.6.7 -fdebug-prefix-map=/srv/conda/envs/notebook=/usr/local/src/conda-prefix -c epsp.c  -fPIC -DPIC -o .libs/epsp.o
/srv/conda/envs/notebook/bin/mpicc: line 282: x86_64-conda_cos6-linux-gnu-cc: command not found
/srv/conda/envs/notebook/bin/mpicc: line 282: x86_64-conda_cos6-linux-gnu-cc: command not found
/srv/conda/envs/notebook/bin/mpicc: line 282: x86_64-conda_cos6-linux-gnu-cc: command not found
/srv/conda/envs/notebook/bin/nrnmech_makefile:84: recipe for target 'CaDynamics_E2.lo' failed
make: *** [CaDynamics_E2.lo] Error 1
make: *** Waiting for unfinished jobs....
/srv/conda/envs/notebook/bin/mpicc: line 282: x86_64-conda_cos6-linux-gnu-cc: command not found
/srv/conda/envs/notebook/bin/nrnmech_makefile:84: recipe for target 'Ca_LVAst.lo' failed
make: *** [Ca_LVAst.lo] Error 1
/srv/conda/envs/notebook/bin/nrnmech_makefile:84: recipe for target 'Ca_HVA.lo' failed
make: *** [Ca_HVA.lo] Error 1
/srv/conda/envs/notebook/bin/nrnmech_makefile:84: recipe for target 'epsp.lo' failed
make: *** [epsp.lo] Error 1
jovyan@jupyter-torbjone-2dlfpy-2dtpgek37p:~/examples/L5bPCmodelsEH/mod$


I haven't looked much into it, but I could not find a way to specify a specific environment.yml file to use.

**Comment by espenhgn** [comment]
Ok, doesn't look like the compiler (`{{ compiler('c') }}`) is included when installing LFPy from conda-forge. It's only installed for the build step in https://github.com/conda-forge/lfpy-feedstock/blob/master/recipe/meta.yaml

So either I update the conda-forge recipe to include or you include it in your environment.yml file for now. I had some problems updating the conda-forge recipe to the latest tagged release (https://github.com/conda-forge/lfpy-feedstock/pull/3) due to some change in the way the builds are generated.

**Comment by torbjone** [comment]
I tried making a new repository that only contained the environment.yml file and the examples, but I was not authorized to make it under github.com/LFPy. Is it possible to get this authorization?

**Comment by torbjone** [comment]
I have now made a repository where several examples can be run:
 
https://github.com/LFPy/LFPy_binder_examples 

I also added a link to the mybinder page in the LFPy README file
