### ISSUE TITLE
Increasing celles in the morphology file

### ISSUE THREAD

**Issue by Robinsondev** [LFPy/LFPy#150]
hello, Sorry to write this as an issue while it is not really one. 
I would like to edit the morphology file, double or triple the umber of cells in order to run multiple simulations in order to know what is the best ratio between inhibitor and excitatory neurons to generate a signal based on the L5_mainen morphology file.
Can you please give me some suggestions how i can do this? 

Thanks

**Comment by torbjone** [comment]
Hi, I'm not sure I understand what you mean, but the morphology file only contains the morphology of one cell, and is typically not edited.

Do you want to run a network simulation with many interacting inhibitory and excitatory neurons, or do you just want to run many single-cell simulations with one L5 cell receiving different numbers of excitatory and inhibitory inputs? In the last case, maybe you can modify the 'examples/example_mpi.py' file to do this?

I'm happy to give you more advice if you have any further questions on this.

**Comment by Robinsondev** [comment]
hi @torbjone i want to run a simulation with many interacting inhibitory and excitatory neurons. Basically in my project i ultimately want to create a simulation that will produce some EEG patterns. 
So I am kind of lost as to how to proceed until i get there. :)

**Comment by torbjone** [comment]
OK, in that case maybe start with trying to run the file 
examples/example_network/example_network.py which contains simplified interacting excitatory and inhibitory neurons. It does not calculate EEG signals, but it calculates the current dipole moments, so obtaining EEG signals is in principle straight-forward. 

It is easy to switch to the L5_mainen cell, but it will be much more time- and memory consuming, so I recommend sticking with the simplified ball and stick models as long as you can.

**Comment by Robinsondev** [comment]
hey @torbjone I hope you are doing great! I had a question about the examples/example_network/example_network.py . I am not very sure what is happening in the code. 
So far i understood that we are using a `ball and stick` model which looks like this 
o------------ 
right?

Next I am trying to understand how the network looks like and how the neurons are connected with each other. So for example, does it look like 
o---------\_o---------
o--------/

Above ai m trying to show 2 balls and stick connected to one ball and stick
            
Is there a way to do something like Neuron.h.shape() or Neuron.h.topology() like in https://www.neuron.yale.edu/neuron/static/py_doc/modelspec/programmatic/topology.html or a way to plot the network.Sorry i am so confused.

**Comment by torbjone** [comment]
Hi, yes the ball-and-stick cell models looks like that. 

These lines say that there will be two populations, E and I, denoting Excitatory and Inhibitory, with 80 and 20 cells respectively:
population_names = ['E', 'I']
population_sizes = [80, 20]

The connection probability between the populations are specified on the form
[["E:E", "E:I"], ["I:E", "I:I"]]. In the example, the line:
connectionProbability = [[0.1, 0.1], [0.1, 0.1]]
says that all cells in each populations will be connected to 10 % of cells in the other populations.

The connectivity matrix between the populations is made with the lines:
            connectivity = network.get_connectivity_rand(
                pre=pre, post=post,
                connprob=connectionProbability[i][j]
                )
and if you want to, you can plot the connectivity matrix like this:
            plt.imshow(connectivity)
            plt.show()
There are four of these, since both the E and I populations are connected to both E and I.

The parameters for the locations of the synapses are specified in the lines:
synapsePositionArguments = [[dict(section=['soma', 'apic'],
                                  fun=[st.norm, st.norm],
                                  funargs=[dict(loc=500., scale=100.),
                                           dict(loc=500., scale=100.)],
                                  funweights=[0.5, 1.]
                                 ) for _ in range(2)],
                            [dict(section=['soma', 'apic'],
                                  fun=[st.norm, st.norm],
                                  funargs=[dict(loc=0., scale=100.),
                                           dict(loc=0., scale=100.)],
                                  funweights=[1., 0.5]
                                 ) for _ in range(2)]]
  which is again on the form [["E:E", "E:I"], ["I:E", "I:I"]].

Does this make any sense to you? If not, I recommend spending some time on reading the LFPy  documentation and the two published papers on LFPy.

**Comment by espenhgn** [comment]
Hi @Robinsondev. Just a couple of clarifications/suggestions. We don't provide any method to plot networks - we primarily wrote the network code for parallel execution on compute clusters, thus rendering the entire network at once would not be very feasible/practical, neither would bringing up neuron gui elements like `neuron.h.Shape`. The `neuron.h.topology()` function works though but it won't draw connections, only schematics of morphologies. 

I'd suggest spending a few minutes to understand the code behind the `Network` class `get_connectivity_rand` and `connect` methods, and perhaps make your own versions for your purpose, like exporting the connections and use a graphing library to analyze/visualize the network.

**Comment by Robinsondev** [comment]
> Hi, yes the ball-and-stick cell models looks like that.
> 
> These lines say that there will be two populations, E and I, denoting Excitatory and Inhibitory, with 80 and 20 cells respectively:
> population_names = ['E', 'I']
> population_sizes = [80, 20]
> 
> The connection probability between the populations are specified on the form
> [["E:E", "E:I"], ["I:E", "I:I"]]. In the example, the line:
> connectionProbability = [[0.1, 0.1], [0.1, 0.1]]
> says that all cells in each populations will be connected to 10 % of cells in the other populations.
> 
> The connectivity matrix between the populations is made with the lines:
> connectivity = network.get_connectivity_rand(
> pre=pre, post=post,
> connprob=connectionProbability[i][j]
> )
> and if you want to, you can plot the connectivity matrix like this:
> plt.imshow(connectivity)
> plt.show()
> There are four of these, since both the E and I populations are connected to both E and I.
> 
> The parameters for the locations of the synapses are specified in the lines:
> synapsePositionArguments = [[dict(section=['soma', 'apic'],
> fun=[st.norm, st.norm],
> funargs=[dict(loc=500., scale=100.),
> dict(loc=500., scale=100.)],
> funweights=[0.5, 1.]
> ) for _ in range(2)],
> [dict(section=['soma', 'apic'],
> fun=[st.norm, st.norm],
> funargs=[dict(loc=0., scale=100.),
> dict(loc=0., scale=100.)],
> funweights=[1., 0.5]
> ) for _ in range(2)]]
> which is again on the form [["E:E", "E:I"], ["I:E", "I:I"]].
> 
> Does this make any sense to you? If not, I recommend spending some time on reading the LFPy documentation and the two published papers on LFPy.

Thanks, i will keep reading it and get back to you. Thanks

**Comment by Robinsondev** [comment]
Hello Guys! thank you so much for the help. I was wondering how to reproduce this:

https://www.frontiersin.org/files/Articles/375040/fninf-12-00092-HTML/image_m/fninf-12-00092-g005.jpg

i found this in the documentation . https://bbp.epfl.ch/nmc-portal/downloads  
So i would like to know how given 2 hoc files for L5 and L4 how to put them together and reproduce the image on the link https://www.frontiersin.org/articles/10.3389/fninf.2018.00092/full in section 3.2.1
 also will it be fair to do something like get_connectivity_rand(self, pre='L5', post='L5', connprob=0.1)
Thanks

**Comment by espenhgn** [comment]
Hi @Robinsondev . Please take a look at the files in https://github.com/LFPy/LFPy/tree/master/examples/bioRxiv281717. Everything needed to reproduce the figures in the paper should be there. But you need access to a compute cluster to be able to run the codes efficiently.

**Comment by Robinsondev** [comment]
Hello, @torbjone @espenhgn, how can i get EEG signals from the examples/example_network/example_network.py ?

I mean something like https://3.bp.blogspot.com/-4eu4tGw0Ov4/VsLSxulGuPI/AAAAAAAAAL8/0PBGm_Gw29E/s1600/hw101.png

Also i am a little confused about the difference current_dipole_moment and EEG signals. Please can you explain? 
thanks so much

**Comment by torbjone** [comment]
Hi, 
the EEG signal, which is what you measure outside the head, is created by the currents in the brain, which are typically formulated as current dipole moments. I recommend the book Electric Fields of the Brain, by Nunez and Srinivasan to understand more about this. 

The EEG can be calculated from the current dipole moments, like is for example done in the example "example_EEG.py", and in "example_network.py", this would mean adding something like:
`
    current_dipole_moment = DIPOLEMOMENT['E'] + DIPOLEMOMENT['I']
    t = np.arange(DIPOLEMOMENT.shape[0])*network.dt
    radii = [79000., 80000., 85000., 90000.]
    sigmas = [0.3, 1.5, 0.015, 0.3]
    rad_tol = 1e-2
    r_mid = np.array([0., 0., 77500])

    eeg_coords_top = np.array([[0., 0., radii[3] - rad_tol]])
    four_sphere_top = FourSphereVolumeConductor(radii, sigmas, eeg_coords_top)
    pot_db_4s_top = four_sphere_top.calc_potential(current_dipole_moment, r_mid)
    eeg_top = np.array(pot_db_4s_top)[0] * 1e3
    fig = plt.figure()
    ax = fig.add_subplot(111, xlabel="Time (ms)", ylabel="$\mu$V", title='EEG')
    ax.plot(t, eeg_top)
    fig.savefig(os.path.join(OUTPUTPATH, 'population_EEG.pdf'), bbox_inches='tight')
`

**Comment by Robinsondev** [comment]
Hello! Happy New year! 

In the documentation for LFPY, it says that if I want to introduce a delay, i can use : 

delayfun [function] function used to draw delays from a numpy.random distribution
delayargs [dict] parameters passed to delayfun
mindelay [float,] minimum delay in multiples of dt

I am trying to make an EEG where I record nothing or very low signals for the first 500 ms, then start the real simulation and simulate for the next 1000ms , then stop and record for the following 500ms. It will idally look like: 


                                           |/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\\/\/\/\\/\/\\////\|
                                           |                                                                   |
                                            |                                                                  |
--------------------------|                                                                  |-------------------------

I tried to introduce a delay of 500 ms doing something like:

networkParameters = dict(
    dt=2**-4,
    tstart = 0.,
    tstop=2000.,
    v_init=-65.,
    celsius=6.5,
    OUTPUTPATH=OUTPUTPATH
)

mindelay = 0.1   # I am not sure how to put 500ms sec here so it can effectively start sending spikes at 500ms up until 1500ms. 
The documentation says mindelay [float,] minimum delay in multiples of dt, what does this mean? I tried to multiply 500*2**-4, but it gives 0.1, I devided 500 by 2**-4 to see what i can get, it was a very big number and the simulation was almost not starting

3.8.8 class Network
class LFPy.Network(dt=0.1, tstart=0.0, tstop=1000.0, v_init=-65.0, celsius=6.3, OUTPUTPATH=’example_parallel_network’, verbose=False)
Bases: object
3.8. Module LFPy 41
LFPy Homepage, Release 2.0.3
connect(self, pre, post, connectivity, syntype=ExpSyn(), synparams={’tau’: 2.0, ’e’: 0.0},
weightfun=<built-in method normal of numpy.random.mtrand.RandomState object at 0x7f163c8abca8>, weightargs={’loc’: 0.1, ’scale’: 0.01}, minweight=0,
delayfun=<built-in method normal of numpy.random.mtrand.RandomState object at
0x7f163c8abca8>, delayargs={’loc’: 2, ’scale’: 0.2}, mindelay=0.3, multapsefun=<builtin method normal of numpy.random.mtrand.RandomState object at 0x7f163c8abca8>,
multapseargs={’loc’: 4, ’scale’: 1}, syn_pos_args={’section’: [’soma’, ’dend’,
’apic’], ’fun’: [<scipy.stats._continuous_distns.norm_gen object at 0x7f163a368c88>,
<scipy.stats._continuous_distns.norm_gen object at 0x7f163a368c88>], ’funargs’: [{’loc’:
0, ’scale’: 100}, {’loc’: 0, ’scale’: 100}], ’funweights’: [0.5, 0.5], ’z_min’: -1000000.0,
’z_max’: 1000000.0}, save_connections=False)
Connect presynaptic cells to postsynaptic cells. Connect

What should I do? 

Thanks

**Comment by torbjone** [comment]
Hi, and happy new year :-)
Those delays are the synaptic delays, meaning that it is the time from the presynaptic cell fires an action potential, to the postsynaptic cell receives the synaptic input. In other words, it is used to model the time it takes the action potential to move along the axon to its target. 

It is possible to set the parameter "tstart" to a negative number, say - 500 ms, and this initial part of the simulation will then not be recorded, that is, recording starts at t=0. 

If you for example want to start some synaptic input to all excitatory cells at around t=500 ms, you could do something like this:

    for cell in network.populations["E"].cells:
        idx = cell.get_rand_idx_area_norm(section='allsec', nidx=64)
        for i in idx:
            syn = Synapse(cell=cell, idx=i, syntype='Exp2Syn',
                          weight=0.2,
                          **dict(tau1=0.2, tau2=1.8, e=0.))
            syn.set_spike_times(np.random.normal(loc=500, scale=10))

Does that help?

**Comment by Robinsondev** [comment]
i will try that now. And get back to you. Thanks

**Comment by espenhgn** [comment]
Just to clarify: `mindelay` has unit of ms, and is used to cap the normal distribution delay values are drawn from for each connection, i.e., in order to avoid `delay <= dt`. If you want to delay activation of your network, turn external activation on at t=500 ms for example. My advice is looking at  https://www.neuron.yale.edu/neuron/static/new_doc/modelspec/programmatic/mechanisms/mech.html#NetStim and https://lfpy.readthedocs.io/en/latest/classes.html#LFPy.Synapse.set_spike_times_w_netstim

**Comment by Robinsondev** [comment]
> Hi, and happy new year :-)
> Those delays are the synaptic delays, meaning that it is the time from the presynaptic cell fires an action potential, to the postsynaptic cell receives the synaptic input. In other words, it is used to model the time it takes the action potential to move along the axon to its target.
> 
> It is possible to set the parameter "tstart" to a negative number, say - 500 ms, and this initial part of the simulation will then not be recorded, that is, recording starts at t=0.
> 
> If you for example want to start some synaptic input to all excitatory cells at around t=500 ms, you could do something like this:
> 
> ```
> for cell in network.populations["E"].cells:
>     idx = cell.get_rand_idx_area_norm(section='allsec', nidx=64)
>     for i in idx:
>         syn = Synapse(cell=cell, idx=i, syntype='Exp2Syn',
>                       weight=0.2,
>                       **dict(tau1=0.2, tau2=1.8, e=0.))
>         syn.set_spike_times(np.random.normal(loc=500, scale=10))
> ```
> 
> Does that help?

At this line, syn.set_spike_times(np.random.normal(loc=500, scale=10)) , I get AssertionError: synapse activation times must be a np.ndarray, not type(<class 'float'>)

Please do not hesitate to check line 390-396 of the following file

[eeg_net.txt](https://github.com/LFPy/LFPy/files/4097243/eeg_net.txt)

Thanks

**Comment by espenhgn** [comment]
Ask yourself: what type does the statement `np.random.normal(loc=500, scale=10)` return?

**Comment by Robinsondev** [comment]
> Just to clarify: `mindelay` has unit of ms, and is used to cap the normal distribution delay values are drawn from for each connection, i.e., in order to avoid `delay <= dt`. If you want to delay activation of your network, turn external activation on at t=500 ms for example. My advice is looking at https://www.neuron.yale.edu/neuron/static/new_doc/modelspec/programmatic/mechanisms/mech.html#NetStim and https://lfpy.readthedocs.io/en/latest/classes.html#LFPy.Synapse.set_spike_times_w_netstim



> Ask yourself: what type does the statement `np.random.normal(loc=500, scale=10)` return?

it returns a number , not an interval. I have tried 

`syn.set_spike_times_w_netstim(noise=1.0, start=500.0, number=10, interval=100.0, seed=1234.0)` 

And i got this:

<img width="595" alt="Screen Shot 2020-01-22 at 8 02 39 AM" src="https://user-images.githubusercontent.com/31787218/72896459-d237a800-3ced-11ea-9583-89a6b953ac82.png">

Which seems realistic i guess. I am right?

**Comment by espenhgn** [comment]
> > Ask yourself: what type does the statement `np.random.normal(loc=500, scale=10)` return?
> 
> it returns a number , not an interval. I have tried

2nd question you need to ask: What input type does the `syn.set_spike_times` method expect?

> 
> `syn.set_spike_times_w_netstim(noise=1.0, start=500.0, number=10, interval=100.0, seed=1234.0)`
> 
> And i got this:
> 
> <img alt="Screen Shot 2020-01-22 at 8 02 39 AM" width="595" src="https://user-images.githubusercontent.com/31787218/72896459-d237a800-3ced-11ea-9583-89a6b953ac82.png">
> 
> Which seems realistic i guess. I am right?

I don't know what kind of result you are plotting. Something happens along the horizontal axis at 500 indeed. Whether or not the result is realistic is up to you to infer, I believe ;-)

**Comment by torbjone** [comment]
Hi,
I did not test the code I suggested, and I had forgotten that it returned a float instead of a numpy array.
This can be fixed by instead using: np.random.normal(loc=500, scale=10, size=1)

**Comment by Robinsondev** [comment]
> > > Ask yourself: what type does the statement `np.random.normal(loc=500, scale=10)` return?
> > 
> > 
> > it returns a number , not an interval. I have tried
> 
> 2nd question you need to ask: What input type does the `syn.set_spike_times` method expect?
> 
> > `syn.set_spike_times_w_netstim(noise=1.0, start=500.0, number=10, interval=100.0, seed=1234.0)`
> > And i got this:
> > <img alt="Screen Shot 2020-01-22 at 8 02 39 AM" width="595" src="https://user-images.githubusercontent.com/31787218/72896459-d237a800-3ced-11ea-9583-89a6b953ac82.png">
> > Which seems realistic i guess. I am right?
> 
> I don't know what kind of result you are plotting. Something happens along the horizontal axis at 500 indeed. Whether or not the result is realistic is up to you to infer, I believe ;-)

For the second question, my understanding is that it gives an interval like [100 .. 1000] , where the first spike is at 500. is it right?

**Comment by Robinsondev** [comment]
> Hi,
> I did not test the code I suggested, and I had forgotten that it returned a float instead of a numpy array.
> This can be fixed by instead using: np.random.normal(loc=500, scale=10, size=1)

Thanks, I have tried this, i used np.random.normal(loc=500, scale=100, size=10) which gives something like 
np.random.normal(loc=500, scale=100, size=10)
array([554.25481487, 455.27063677, 435.05541882, 323.38040507,
       391.43367464, 714.51739266, 571.18807605, 566.97841764,
       608.63683202, 421.59116408])

so in order to try to have something over the interval of [500 .. 1500], i tried np.random.normal(loc=1000, scale=500, size=10). i got the following figure 

![Figure_1](https://user-images.githubusercontent.com/31787218/72901386-ab7e6f00-3cf7-11ea-837d-9216d5bbf0d4.png)

I am going to read more to see which one is morealistic between that and 

![Figure_2](https://user-images.githubusercontent.com/31787218/72901608-1465e700-3cf8-11ea-92df-55ea363d8a3f.png)

Thanks. I will be back. I am reading the book Electric fields of the brain by Nnez and Srinivasan. :)

**Comment by Robinsondev** [comment]
Hi, I have a more general question regarding EEG's. So the literature says that on a normal basis, with no excitation at all, there is some small activity happening in the brain. The way I picture it, is that instead of having nothing until I set the spike times say starting at t=500ms, so instead of starting at 500ms, i start at zero with some current input that is 10 time smaller than the regular input i would have at 500ms.

 **this will be something like :**
if time < 500 then
 spike instensity=  0.1
if time >= 500 then 
 spike instensity = 1 (ten teimes for time  <500)

 Based on my understanding of LFPY this will mean that we would try to alter the synaptic connection between neurons (SYNAPTIC WEIGHT)  since I could not see a function to reduce spike intensity. Please correct me if I am wrong. 

So I tried something that I know won't work: 

`for cell in network.populations["E"].cells:
                idx = cell.get_rand_idx_area_norm(section='allsec', nidx=64)
                for i in idx:
                    if t < 500 :
                        syn = Synapse(cell=cell, idx=i, syntype='Exp2Syn',
                                      weight=0.02, 
                                      **dict(tau1=0.2, tau2=1.8, e=0.))
                        syn.set_spike_times(np.random.normal(loc=250, scale=50, size=5))
                    else:
                        syn = Synapse(cell=cell, idx=i, syntype='Exp2Syn',
                                      weight=0.2, #(weight 10 time bigger than for t<500)
                                      **dict(tau1=0.2, tau2=1.8, e=0.))
                        syn.set_spike_times(np.random.normal(loc=1000, scale=500, size=10))

Please can you suggest something or point somewhere? :) Thanks

**Comment by Robinsondev** [comment]
> Hi, I have a more general question regarding EEG's. So the literature says that on a normal basis, with no excitation at all, there is some small activity happening in the brain. The way I picture it, is that instead of having nothing until I set the spike times say starting at t=500ms, so instead of starting at 500ms, i start at zero with some current input that is 10 time smaller than the regular input i would have at 500ms.
> 
> **this will be something like :**
> if time < 500 then
> spike instensity= 0.1
> if time >= 500 then
> spike instensity = 1 (ten teimes for time <500)
> 
> Based on my understanding of LFPY this will mean that we would try to alter the synaptic connection between neurons (SYNAPTIC WEIGHT) since I could not see a function to reduce spike intensity. Please correct me if I am wrong.
> 
> So I tried something that I know won't work:
> 
> `for cell in network.populations["E"].cells:
> idx = cell.get_rand_idx_area_norm(section='allsec', nidx=64)
> for i in idx:
> if t < 500 :
> syn = Synapse(cell=cell, idx=i, syntype='Exp2Syn',
> weight=0.02,
> **dict(tau1=0.2, tau2=1.8, e=0.))
> syn.set_spike_times(np.random.normal(loc=250, scale=50, size=5))
> else:
> syn = Synapse(cell=cell, idx=i, syntype='Exp2Syn',
> weight=0.2, #(weight 10 time bigger than for t<500)
> **dict(tau1=0.2, tau2=1.8, e=0.))
> syn.set_spike_times(np.random.normal(loc=1000, scale=500, size=10))
> 
> Please can you suggest something or point somewhere? :) Thanks

Hi Guys!, fast forward, I have tried something : 

            tot_dt = 0
            for cell in network.populations["E"].cells:
                idx = cell.get_rand_idx_area_norm(section='allsec', nidx=64)
                for i in idx:
                    tot_dt = tot_dt + 5 # 5 refers to the timestep dt which is the response time for every spike, same value as dt above
                    if tot_dt < 500 and tot_dt > 1500:
                        syn = Synapse(cell=cell, idx=i, syntype='Exp2Syn',
                                      weight=0.02,
                                      **dict(tau1=0.2, tau2=1.8, e=0.))
                        syn.set_spike_times(np.random.normal(loc=250, scale=250, size=100))
                        # syn.set_spike_times(np.random.normal(loc=1000, scale=500, size=10))
                    elif tot_dt >= 500 and tot_dt<=1500 :
                        syn = Synapse(cell=cell, idx=i, syntype='Exp2Syn',
                                      weight=0.2,
                                      **dict(tau1=0.2, tau2=1.8, e=0.))
                        # syn.set_spike_times(np.random.normal(loc=250, scale=50, size=5))
                        syn.set_spike_times(np.random.normal(loc=1000, scale=500, size=10))

 I obtained the following figure:

![Figure_different synapse_weight](https://user-images.githubusercontent.com/31787218/72975018-11253680-3d9e-11ea-99fe-c2cb10ebd628.png)

However it does not work for dt too small (less than 0.1 ms). For example for dt= 0.02, I get:


![Figure_dt_small](https://user-images.githubusercontent.com/31787218/72976353-724e0980-3da0-11ea-8825-30c9fba4d89d.png)

I am investigating this. 

Please can you give me insight on how I can make this better?

Thanks

**Comment by torbjone** [comment]
Hi, you should probably not change the synaptic weights, just the external input.

For example, each cell could have synapses that supplies background inputs: 
syn.set_spike_times_w_netstim(noise=1.0, start=0.0, interval=10.0, seed=1234.0)
and other synapses that gets additional synaptic input around a specific time:
syn.set_spike_times(np.random.normal(loc=1000, scale=20, size=10))

**Comment by Robinsondev** [comment]
Hello! 

I tried to do a simulation with the method above. The issue is i am trying to simulate something like the following image :

![image](https://user-images.githubusercontent.com/31787218/73206704-68663680-4111-11ea-9fc6-4fca81b14723.jpg)

Which initially from 0 to 499ms can have an input of say 0.1 volt and from 500ms to 1500ms can have say 1volt. And then feom 1500ms to 2000ms we are back to 0.1ms.

**Comment by torbjone** [comment]
Hi, 
I'm not sure I understand what you mean with an input of 0.1 (or 1) volt. Do you mean an external voltage-controlled electrode that are stimulating neurons, or do you mean that the simulated EEG should go from 0.1 V to 1 V when the amount of synaptic input increases at 500 ms?

**Comment by Robinsondev** [comment]
Hi,

Sorry! No i meant, for example when we make a stimation, we cannot really know how much voltage will come out of it. So the idea, is assuming the max voltage is 1, and the min voltage is 0.1 over a network. I want to run a simulation such that from 0-499ms, we have 0.1, then from 500ms to 1500ms we have 1, then from 1501 to 2000, we have 0.1 again. This means we have some minor brain activity from 0-500ms but at 500ms, we actually start simulating the network continuously for 1000ms, so we can then see what happens. 🙂

**Comment by Robinsondev** [comment]
So one thing I was thinking my be an issue with using:

syn.set_spike_times_w_netstim(noise=1.0, start=0.0, interval=10.0, seed=1234.0)
and other synapses that gets additional synaptic input around a specific time:
syn.set_spike_times(np.random.normal(loc=1000, scale=20, size=10))

is that it kind of means we are expecting a maximum spike at a specific time. 

Also another issue I found is that if I want to start simulations at 500ms and expect a peak spike anywhere near 1000, I tried using  
syn.set_spike_times(np.random.normal(loc=1000, scale=20, size=10))
but then the issue is that if you coI need to find a range, or mean value so that the simulation increase starts exactly at 500, i tried a bunch of different values as the mean but  and i found the value is somewhere between 100 and 250. However a correctponding graph does not look like we stop simulations at 1500. Please see graph below. 
In the graph below, the center is at 1500

![Figure_1_yoio](https://user-images.githubusercontent.com/31787218/73279680-7cff0900-41bb-11ea-8339-2b134ce4d582.png)

**Comment by torbjone** [comment]
Since these are very problem-specific questions, I suggest we just take it on email instead. You can reach me at torbjorn.ness at NMBU.no :-)

**Comment by espenhgn** [comment]
@torbjone Thank you!
