### ISSUE TITLE
Test failures on ppc64le and armv7hl

### ISSUE THREAD

**Issue by sanjayankur31** [LFPy/LFPy#173]
Hello,

While building LFPy for [NeuroFedora](https://docs.fedoraproject.org/en-US/neurofedora/overview/), we're seeing tests fail, but only for ppc64le and armv7hl. While the mod files required for the tests are correctly compiled, it looks like they're not correctly loaded by the hoc module when the tests are run. Could you please take a look? I'm not sure if this is a neuron issue or something in LFPy.

- "scratch build": https://koji.fedoraproject.org/koji/taskinfo?taskID=44760761
- Successful build: [lfpy-build-log-x86_64.txt](https://github.com/LFPy/LFPy/files/4661725/lfpy-build-log-x86_64.txt)

- Failed builds: [lfpy-build-log-armv7hl.txt](https://github.com/LFPy/LFPy/files/4661730/lfpy-build-log-armv7hl.txt), [lfpy-build-log-ppc64le.txt](https://github.com/LFPy/LFPy/files/4661731/lfpy-build-log-ppc64le.txt)

This is LFPy version 2.0.7.

**Comment by espenhgn** [comment]
Hi @sanjayankur31, 
I had removed support for powerpc and 32bit platforms in v2.0.7 as I didn't think they were needed by anyone/anything: 
https://github.com/LFPy/LFPy/commit/9e25ca629703dc78109745b48eb7514a17cec23d#diff-2eeaed663bd0d25b7e608891384b7298L39

I can easily revert this change though and make it into a future release 2.1 which we are currently working on. I'm not sure if it makes sense for us to continue the 2.0.* development. We've also removed support for Python 2.7 in the master branch.

**Comment by sanjayankur31** [comment]
> Hi @sanjayankur31,
> I had removed support for powerpc and 32bit platforms in v2.0.7 as I didn't think they were needed by anyone/anything:
> [9e25ca6#diff-2eeaed663bd0d25b7e608891384b7298L39](https://github.com/LFPy/LFPy/commit/9e25ca629703dc78109745b48eb7514a17cec23d#diff-2eeaed663bd0d25b7e608891384b7298L39)
> 
> I can easily revert this change though and make it into a future release 2.1 which we are currently working on. I'm not sure if it makes sense for us to continue the 2.0.* development. We've also removed support for Python 2.7 in the master branch.

Hi @espenhgn , thanks for the quick reply.

I missed that change. Sorry.  There's no need to re-enable them if you don't think they are worth supporting. I'll just disable them in Fedora too.

We're only doing Py3 now, so not supporting Py2 is perfectly fine. Fedora 33, the next release, is currently tracking Python3.9.

**Comment by sanjayankur31** [comment]
Disabled 32 bit and powerpc in Fedora. Closing this.
