### ISSUE TITLE
Test with NEURON 7.8

### ISSUE THREAD

**Issue by alejoe91** [LFPy/LFPy#205]
Hi @espenhgn 

Reporting some issues running LFPy with NEURON 7.8 (inside MEArec). Basically all extracellular signals are nan.
The tests work well with version <= 7.7, so I guess there must be some issue with the NEURON version.

Could you double check that?

Thanks!

**Comment by espenhgn** [comment]
Hi @alejoe91 . 
Something is indeed broken with NEURON 7.8. I opened #183 some time ago, but I haven't looked into it as neuron 7.7.2 is still the most current version on conda-forge. Didn't see that 7.8 is now official.

**Comment by espenhgn** [comment]
Also, travisCI builds are now unexpectedly broken....

**Comment by espenhgn** [comment]
Does your issue look similar to the one I encountered? If the way morphology data is supposed to be extracted from NEURON has changed, then one can get NANs in LFPy if segment lengths all of a sudden is 0. 
Anyway, I'm trying to figure out why travisCI fails. I think the Neuron module is looking for some C compiler that is not available anymore from conda-forge.

**Comment by alejoe91** [comment]
Yes, but I get NaNs in the extracellular signals...
