### ISSUE TITLE
Documentation bug: Broken link to examples

### ISSUE THREAD

**Issue by torbjone** [LFPy/LFPy#234]
On the bottom of https://lfpy.readthedocs.io/en/latest/tutorial.html there are links to example *.py files, but these files have been converted to jupyter notebook files, and links are therefore broken.

**Comment by espenhgn** [comment]
Hi. The up to date documentation for the current dev branch (`2.2.dev0`) is here: https://lfpy.readthedocs.io/en/2.2.dev0/
The new documentation is now just the top-level README.md file with the class/method documentation (including LFPykits').
