### ISSUE TITLE
Include simple plotting tools in LFPy?

### ISSUE THREAD

**Issue by torbjone** [LFPy/LFPy#235]
To enable quick development and less redundancy, maybe we should consider including some often used plotting functions? Some of the suggestions below are not directly LFPy related, but would still potentially simplify workflows in making figures

Examples of plotting stuff that I use very often:
- Plot morphology to given axes (potentially with different colors for different cell parts)
- Mark subplots with letters
- Remove right and top axis borders
- Plot laminar LFP to given axes

In addition, during exploratory phases of projects, when I test different morphologies, I often make plots with the same cell seen from different angles, sometimes with the name of different sections specified. 

What do you think?

**Comment by espenhgn** [comment]
Check out @alejoe91's https://github.com/LFPy/neuroplotlib ;-)

I'm all for having a LFPy specific plotting library, but I think it should be an external one. I'd a bit hesitant to include matplotlib as a run time dependency especially for use on compute nodes where DISPLAY may be unset. I know MEAutility which is installed alongside LFPy uses matplotlib, but it's at least a lazy import in MEAutility. 

Also, a big effort into this may be somewhat redundant, as NEURON now has a gui2 module in an effort to modernize their archaic UI.

**Comment by torbjone** [comment]
Ah, thank you, there everything was :-)

**Comment by espenhgn** [comment]
Good :) 
neuroplotlib will need some updates for LFPy@2.2.dev0 though. But plotting cell geometries should be even simpler now:
![image](https://user-images.githubusercontent.com/2492641/95556937-5d8bd180-0a14-11eb-952d-b8421b45b8e9.png)
LFPy.Synapse objects also keep track of their location in space as `synapse.x` etc.

**Comment by alejoe91** [comment]
Hi guys!

Yeah we should update it to v2.2dev. What are the main changes? having `x`, `y`, `z`? if I understand correctly `x = [xstart, send]`. Right?

**Comment by espenhgn** [comment]
@alejoe91; yes, these attributes should now in LFPy be 2d arrays with shape (nsegs, 2). Also `diam` is renamed `d` in line with https://lfpykit.readthedocs.io/en/latest/#class-cellgeometry. `d` can be 2D in LFPykit which was needed for Arbor, as arbor treats electric compartments as variable diameter. Also the `xmid` attribute is gone. If you need it just compute the mean position along the last axis (`cell.x.mean(axis=-1)`)
