### ISSUE TITLE
Should LFPy provide all these high level NEURON classes?

### ISSUE THREAD

**Issue by Helveg** [LFPy/LFPy#247]
LFPy provides a very nice LFP probe, but it depends on alot of peripheral classes such as `Cell` or `Synapse`. I'm looking to integrate your LFP probe into my own framework but I will probably be hindered by those classes. Would LFPy's main feature, an LFP probe, not shine brighter and be easier to incorporate in any generic model if it could either function as a standalone probe, or depend on less specialized objects with an interface that is clearer and easier to comply with?

### Standalone

I don't see exactly why these additional classes are required? Couldn't the NEURON objects themselves that should be considered by the probe be passed? 

Couldn't the probe be refactored to take a list of `nrn.Sections` / `nrn.PointProcesses` that it should measure rather than the Cell classes? If these higher level classes do offer some added value, it's certainly not true in all use cases so splitting LFPy into 2 layers might improve its usability: 1 layer that uses NEURON objects so that anyone can implement it in their model, and 1 higher level API that offers extra user friendliness to those looking to use LFPy as a full simulation framework.

### Improved interface

Quickly glancing over the source code it looks like a lot of pieces need to be present on `Cell` classes to be used with the recorder probe. Why not define a few functions that return the required information from the object like a `get_sections()` and `get_point_processes()` function that then yield the lower level NEURON objects to be taken into account. That way it's easier for 3rd party developers to use LFPy library style and to pass an object into LFPy with those functions present :)

**Comment by Helveg** [comment]
I think what I'm addressing here is what LFPykit is supposed to offer? I'll take a look at that, sorry :)

**Comment by espenhgn** [comment]
Yes, perhaps LFPykit is what you're seeking - freestanding implementations of different electrostatic forward-models without runtime dependencies on NEURON or LFPy.
