### ISSUE TITLE
Warnings should not be `raise`d, use the warnings module instead

### ISSUE THREAD

**Issue by Helveg** [LFPy/LFPy#248]
`cell.py` has a section that raises `DeprecationWarning`s, even though `Warning`s do inherit from the `Exception` class they should not be raised like exceptions. Instead the builtin `warnings` module should be used. This is more in line with the intended use of warnings; namely to report but not interrupt the control flow. On top of that the warnings module allows the user to decide how to deal with the warnings like to ignore them or not. You can always create a class extended from `Exception` and call it `DeprecationError` if you really want to error out on a deprecation notice (or ofcourse continue using the `DeprecationWarning` for it then :smile: )

**Comment by espenhgn** [comment]
There may be some bad use of DeprecationWarning still in the 2.2.dev0 branch, where some kwargs to Cell.simulate has been removed/added (and possibly other places). Will keep it in mind.

**Comment by espenhgn** [comment]
Closed by merging #226
