### ISSUE TITLE
Overzealous type checking

### ISSUE THREAD

**Issue by Helveg** [LFPy/LFPy#250]
There's often asserts of types, mostly `float`, `int`, `list` and `np.ndarray` checks, but those will fail in cases where the input could've been valid (in the simplest case an iterator) and strict type checks like that are considered unpythonic. In Python it's usually better to just see whether the object allows the operation you're trying to perform.

Take

```python
        if type(sigma) in [list, np.ndarray]:
            self.sigma = np.array(sigma)
            if not self.sigma.shape == (3,):
                raise ValueError("Conductivity, sigma, should be float "
                                 "or array of length 3: "
                                 "[sigma_x, sigma_y, sigma_z]")
```

as an example. `sigma = (i for i in range(3))` would fail this while:

```python
try:
  self.sigma = float(sigma)
except:
  try:
    self.sigma = np.array(sigma)
    if self.sigma.dtype == object and self.sigma.shape[0] == 1:
      self.sigma = np.fromiter(sigma)
  except:
    raise ValueError("Could not convert the given sigma into a float or numpy.ndarray")
```

Would capture alot more different types than just `list` and `ndarray` that can all be validly converted into numpy arrays.

**Comment by espenhgn** [comment]
Probably a good idea. I would have preferred type hints (https://www.python.org/dev/peps/pep-0484/) but it would be a bit of effort and it looks like it would depend on some external module for numpy types such as https://github.com/predictive-analytics-lab/data-science-types or https://pypi.org/project/nptyping/
