### ISSUE TITLE
`exec` statements where `setattr` would do?

### ISSUE THREAD

**Issue by Helveg** [LFPy/LFPy#252]
There's 2 occurences of `exec` that seem to be equivalent to `setattr`

_(And a similar `eval` right above the first example)_
https://github.com/LFPy/LFPy/blob/645f1b4c2f4aed5c356d6a9afd53b22631042c5f/LFPy/cell.py#L658

https://github.com/LFPy/LFPy/blob/645f1b4c2f4aed5c356d6a9afd53b22631042c5f/LFPy/network.py#L206

Both of these should call `setattr` anyway and it's probably clearer and faster to use `setattr` directly.

**Comment by espenhgn** [comment]
Fixed in master branch by merging #226
