### ISSUE TITLE
RecMEAElectrode and MEAutility not cooperating

### ISSUE THREAD

**Issue by torbjone** [LFPy/LFPy#280]
The example "example_ECoG.py" is broken. It runs, but the results returned from the MoI version (with cortical surface included) makes no sense. However, it works fine if the electrodes have no extent.

I think the reason is that the RecMEAElectrode class is not working properly with the MEAutility. The "z_shift" parameter is used in RecMEAElectrode to temporarily shift the coordinate system, but this is not taken into account when MEAutility is finding points inside the electrode surface. 

I think an easy fix would be to do the coordinate shift in the "calc_lfp_pointsource_moi"-function instead with "z_shift" as a kwargs. If everyone is OK with this solution, I can try to implement it with some additional tests next week.

**Comment by espenhgn** [comment]
Thanks @torbjone. If you find a fix that would be great. Not quite sure how this happened as I don't remember to have changed anything with the `z_shift` parameter (or with MEAutility for that matter). 

I see in `RecMEAElectrode.get_transformation_matrix()` the cell is indeed translated along the z-axis, before calling `_lfp_el_pos_calc_dist` or `_loop_over_contacts` but that it does not have the correct effect seems odd.

**Comment by torbjone** [comment]
Just to clarify, this bug did not arise now, but has probably been here at least a few months.
Within the function '_lfp_el_pos_calc_dist' is this line: 'points = self.probe.get_random_points_inside(self.n)'
and my impression is that the electrode locations calculated in "self.probe" do not see the shift, although I will look more into it now.

**Comment by espenhgn** [comment]
Ok, that'd be great. A simple check would be that the calculated potential should converge to the point-contact potential if the radius of the contact(s) is set to a very small value.

**Comment by alejoe91** [comment]
Hi guys, I think that @torbjone is right. I don't see the `z_shift` arg being passed to the `MEAutulity` object. 

A simple fix would be calling:

```
self.probe.move([0, 0, z_shift]) 
```

after the super init here: https://github.com/LFPy/LFPykit/blob/master/lfpykit/models.py#L1188

@torbjone can you check if this addition fixes the bug?

**Comment by torbjone** [comment]
Hi,
thanks Alesssio! That would probably work as well, but after having thought about this, I think it makes most sense to just do the shift where the calculation of the extracellular potential is done, since this is purely a mathematical trick. I was able to fix this by doing the shift in 'calc_lfp_*_moi'.

I have a branch of LFPy with the additional tests and slight example fixes here: https://github.com/torbjone/LFPy/tree/dev2.2rc3
and I have a branch of LFPykit with the fixed shifting here: https://github.com/torbjone/LFPykit/tree/z_shift_fix 

Should I just make to separate pull requests, or is there a better way?

**Comment by alejoe91** [comment]
I think you have to make separate PRs :)

I would first open the PR on LFPykit, then the one on LFPy referencing the LFPykit PR

**Comment by espenhgn** [comment]
Agree, the PR needs to be against LFPykit@master for future LFPy-2.2, not LFPy (unless you also want to fix it at LFPy@2.1.2 for a bugfix release 2.1.3)

**Comment by espenhgn** [comment]
@torbjone , please close if you're done fixing.

**Comment by espenhgn** [comment]
Closing. Fixed by merging https://github.com/LFPy/LFPykit/pull/110 into LFPykit.
