### ISSUE TITLE
Attribute error while importing modules from LFPy

### ISSUE THREAD

**Issue by RichaS19** [LFPy/LFPy#286]
The command "import LFPy" has been successful, but when I am giving commands to get other modules from it, it is either showing "ModuleNotFoundError: no module named LFPy.Cell" or "AttributeError: module 'LFPy' has no attribute 'Cell' " or "ImportError: cannot import 'Synapse' or 'Cell' "
Could you please tell me what did I miss?

Thank you.

**Comment by espenhgn** [comment]
Hi. Can you describe the exact steps you took to install LFPy? Sounds like LFPy is not installed, and LFPy is a folder in your working directory

**Comment by RichaS19** [comment]
I tried with pip install LFPy - It didn't work; since it showed error - "failed to build wheel for mpi4py....something like that". So, I guess I used conda install LFPy.
I downloaded the LFPy folder from GitHub codes. I see! but If it's not installed, will it not throw an error on the "import LFPy" command?

**Comment by espenhgn** [comment]
There are some issues at hand here:
1. If you are using anaconda and issue `conda install lfpy` in your conda environment (see pt. 5 here: https://lfpy.readthedocs.io/en/latest/readme.html#installation), all dependencies should be installed with LFPy if the platform is supported (which it *should* be in your case). Your safest bet is *not* to install absolutely everything in the "base" environment mixing pip and conda install. Create a separate env for LFPy and install what you need there.  
2. If you pip install LFPy, it will pip install it's Python dependencies if not found. But unlike conda, pip won't install system MPI libraries for instance, hence mpi4py fail to install.

**Comment by RichaS19** [comment]
I deleted everything and started all over again, and as suggested by you, I tried installing from pip and it is still giving me the error for mpi4py and there is this new error with pillow. 
the error says "The headers or library files couldn't be found for jpeg" while installing pillow and same error for mpi4py "couldn't build wheel for mpi4py" and several other red lines stating these two didn't set up. and of course, thus LFPy wasn't installed!
Could you please help me with this?!
Thanks.

**Comment by espenhgn** [comment]
Why don't you simply issue `conda install lfpy` as in the documentation I pointed you to? As I said `pip` won't install missing system libraries for you (only python packages). You have to do that yourself using brew or whatever. A useful tip is to first google the error messages you're now seeing - they are unlikely to be directly related to LFPy itself.

**Comment by espenhgn** [comment]
@RichaS19 , did you figure out a solution in the end?

**Comment by RichaS19** [comment]
Hello,
Yes, somehow!
But ultimately its an issue with mac version since it couldn't install the packages of new versions as required by LFPy. so I have managed to install LFPy with the versions that could work with my system. So, it worked and it is importing the submodules too.
Now, while writing checking it with one of the source code, it is giving error by raising exception with self._load_geometry(); which is to where it is fixing path on windows, are we supposed to comment that out or am I missing some other package or anything like that, whats the way to surpass that because it's not windows. I was just looking into all the issues here but i am not sure if anyone has raised this. Could you please help me with this?

Thank you!

**Comment by espenhgn** [comment]
Not sure if I understand your problem with the `LFPy.Cell._load_geometry()` method. Please elaborate. Nothing in that function is specific to Windows: https://github.com/LFPy/LFPy/blob/133f90172789e5be3e326c580c0926d0769a65a9/LFPy/cell.py#L317

**Comment by RichaS19** [comment]
![Screen Shot 2020-12-08 at 6 38 51 pm](https://user-images.githubusercontent.com/75294807/101487083-a2d06f00-3983-11eb-8603-fc439d78b8eb.png)

**Comment by RichaS19** [comment]
this is where it raised exception

**Comment by RichaS19** [comment]
> Not sure if I understand your problem with the `LFPy.Cell._load_geometry()` method. Please elaborate. Nothing in that function is specific to Windows:
> 
> https://github.com/LFPy/LFPy/blob/133f90172789e5be3e326c580c0926d0769a65a9/LFPy/cell.py#L317

**Line 193-203**

**Comment by RichaS19** [comment]
![Screen Shot 2020-12-08 at 6 54 15 pm](https://user-images.githubusercontent.com/75294807/101488592-cbf1ff00-3985-11eb-8acc-52c485ddc753.png)

This was what I tried and got the error which lead me to read those 193-203 lines in cell.py. 
Pardon me if its very minor and I overlooked :)

**Comment by espenhgn** [comment]
That last line tells you everything you need. The path to the morphology file you define is wrong.

**Comment by RichaS19** [comment]
Yeah, that was my first intuition, thus I am trying more. I have first done it with the entire path (taken from the file itself)- still showed the same. Its something with syntax or something, i'll see.

**Comment by torbjone** [comment]
Hi, the path to the file should either be the absolute path, or relative to the folder that you are executing your file from. From how the path looks like now, the notebook that you are running should be stored and executed from the folder which has the "LFPy-master" folder. Is that correct in this case?

**Comment by RichaS19** [comment]
Yes it is.
so you mean if am already in that folder, all i need is to lead the path further to the file itself, right? Although I have tried all possible ways for it to know that path, but it's still giving the same error.

**Comment by torbjone** [comment]
You can check if you have the right path by checking if os.path.isfile(path_to_morphology) returns True. If it returns False, you need to fix the path. If so, can you post the absolute path to your morphology file and your notebook file?

**Comment by RichaS19** [comment]
Ah I see. it showed false.
The absolute path to access the morphology is /Users/Richa/LFPy-master/examples/morphologies
I gave the following command too- 
'morphology': os.path.join('Users/Richa/LFPy/examples/morphologies',
                                    'L5_Mainen96_LFPy.hoc'),

and the error is same as shown in the screenshot.

and the path of the notebook is - /Users/Richa/LFPy-master/examples
What am I missing?

**Comment by torbjone** [comment]
Presumably it should be "LFPy-master" in the "morphology" parameter line? No it says just "LFPy".
I think you need to use "/Users" instead of "Users", otherwise it will look for a folder called "Users" where you executed your file.

**Comment by RichaS19** [comment]
Thaaaank you for pointing that out, it worked now! :)

Could you please be able to look at the first error too (in the screenshot); Sorry for troubling this much, I am very new to this and its hard to find these errors simple by googling.

**Comment by RichaS19** [comment]
![Screen Shot 2020-12-09 at 3 46 18 pm](https://user-images.githubusercontent.com/75294807/101616223-1ed6bf80-3a35-11eb-9b81-4a4894e49c87.png)

**This one**

**Comment by espenhgn** [comment]
Hi, 
That error you're seeing is because your installed LFPy version is most likely 2.1.2 from conda. You're basing your notebook from examples in the current master branch (LFPy-2.2 in the future) which is not fully compatible with LFPy-2.1.2. Please base your code off the correct LFPy version, i.e., https://github.com/LFPy/LFPy/releases/tag/v2.1.2

**Comment by RichaS19** [comment]
Oh okay. 
No I installed using pip and got the example code from- https://github.com/LFPy/LFPy 

Thank you so much.

**Comment by RichaS19** [comment]
Also, LFPykit and MEAutility will be the same for v 2.1.2, right? Although they are named as LFPykit-masters & MEAutility-masters.

**Comment by espenhgn** [comment]
LFPykit is not used by LFPy-2.1.2. The version from PyPI (using pip) is identical to the one from conda.
If you git cloned our repository you should issue `git checkout v2.1.2` to get the correct version of all example files.

**Comment by espenhgn** [comment]
MEAutility should be allright.

**Comment by RichaS19** [comment]
Okay. Thanks!

**Comment by espenhgn** [comment]
Closing. Original issue appears to have been resolved.
