### ISSUE TITLE
Building network issue.

### ISSUE THREAD

**Issue by m-bellv** [LFPy/LFPy#287]
Hello,

I am trying to build a network as per the example: 
https://github.com/LFPy/LFPy/blob/master/examples/example_network/example_network.py#L254

I am getting the error:

  File "/home/mbell/anaconda3/lib/python3.8/site-packages/LFPy/network.py", line 582, in create_population
    self.pc.cell(gid, cell.sd_netconlist[-1])

IndexError: List[1]

the network.py contains the same as in https://github.com/LFPy/LFPy/blob/master/LFPy/network.py (I copied code to be sure)

I am using ubuntu and installed lfpy using the pip install lfpy in my terminal. I am running python using spyder from anaconda navigator, the version= "2.1.2"

**Comment by espenhgn** [comment]
Hi @m-bellv. My understanding is that @torbjone helped you with this issue by email. Closing this then.
