### ISSUE TITLE
Incorporate method of images for point- and linesources

### ISSUE THREAD

**Issue by espenhgn** [LFPy/LFPy#30]
`LFPy.RexExtElectrode` class and corresponding methods should be extended with method of images for computing extracellular potentials with planar discontinuities in the extracellular medium. See if we can make @torbjone implementation https://github.com/torbjone/MoI an install dependency.

**Comment by torbjone** [comment]
This issue has been taken care of in a pending PR.

**Comment by espenhgn** [comment]
Fixed by PR #40. Closing.
