### ISSUE TITLE
Potential installation/environment-related bug (conda)

### ISSUE THREAD

**Issue by cjayb** [LFPy/LFPy#319]
**Describe the bug**

Tests are failing due to missing NEURON objects (?). 

```python
...
AttributeError: 'hoc.HocObject' object has no attribute 'SinSyn'
...
AttributeError: 'hoc.HocObject' object has no attribute 'ExpSynI'
...
```

**To Reproduce**

```bash
$ conda create -n lfpy python=3 pip lfpy  # creates new Python 3.x conda environment named lfpy with pip and LFPy and their dependencies
$ conda activate lfpy  # activate the lfpy environment
$ python -c "import LFPy; LFPy.run_tests()"  # check that installation is working
```

**Desktop/Environment (please complete the following information):**

 - OS: macOS
 - otherwise as above (`conda-forge`, ran 4 March 2021)

**Additional context**
 
I was trying to run [the recent Naess et al. EEG-paper examples](https://github.com/solveignaess/EEG/blob/915a90f97610de0561d00df5764d2180b5d29007/src/make_data_figure2.py)

```python
AttributeError: 'RecExtElectrode' object has no attribute 'calc_lfp'
```

which seems to be a separate issue, though.

**Comment by espenhgn** [comment]
Hi @cjayb. Which mac, macOS and Anaconda versions are you using? I just retraced your steps (macbook pro 13 2016, macOS 10.14.6; conda 4.9.2) and could run the test suite without issues. 

As for the Næss codes, they are probably not yet patched to the latest LFPy-2.2 which changed some syntax. You could try and request the older LFPy release from the conda forge or PyPi (e.g. `conda install lfpy==2.1.*`)

**Comment by cjayb** [comment]
Hej Espen, macOS 10.15.7 (sorry I left that out...), conda 4.9.2.

I nuked my conda installation and started from scratch: tests and examples now running fine. I guess I must have had a ghost NEURON installation in there somewhere messing things up.

Sorry about the noise, and thanks for your rapid response! Closing now.

**Comment by espenhgn** [comment]
Hi, no problem! If you encounter any other problem with LFPy don't hesitate to let us know.

**Comment by tanmoysil** [comment]
I am having the same issue. I have also tried everything from my knowledge including installing everything in another mac but i am still getting the issue.

os- mac big sur
conda 4.10.1

lfpy.run_test() is returning these errors:
1. AttributeError: 'hoc.HocObject' object has no attribute 'SinSyn'
2. AttributeError: 'hoc.HocObject' object has no attribute 'ExpSynI'

also while running one of the tutorial codes i am encountering the following error:
1. AttributeError: 'RecExtElectrode' object has no attribute 'calc_lfp'


can someone please help? @cjayb @espenhgn

**Comment by espenhgn** [comment]
Hi @tanmoysil; Thanks for raising this issue. Seems like conda is not installing the latest version of NEURON even in a fresh environment for some reason. In my case I got
```
$ conda list
... 
clang                     11.1.0               h694c41f_0    conda-forge
...
lfpy                      2.2.1           mpi_openmpi_py39hb500004_0    conda-forge
...
neuron                    7.8.2           mpi_openmpi_py39h75a758c_1    conda-forge
```
But there are multiple newer versions matching the pattern  
```
neuron                         7.8.2 mpi_*_py3*_2  conda-forge   
```
returned by`conda search neuron`. I don't quite understand why the "lesser" build (implied by the last digit) get installed but the immediate quick fix seems to be a forced upgrade of NEURON like so:
```
conda install neuron='7.8.2 mpi_*_2'
```
With this version of NEURON the LFPy tests run and also the NEURON GUI should also work (try `neurondemo`). 
The core problem is that the older NEURON builds used clang 9, while this is now clang 11 which then results in incompatible compiled files (such as the ExpSynI extension). 

Ultimately, it looks like I will have to modify the recipe at https://github.com/conda-forge/lfpy-feedstock. I've raised an issue at https://github.com/conda-forge/lfpy-feedstock/issues/24

**Comment by tanmoysil** [comment]
Hi Espen
Everything seems to work fine with the force upgrade. Thanks for the quick resolve and response.

**Comment by espenhgn** [comment]
> Hi Espen
> Everything seems to work fine with the force upgrade. Thanks for the quick resolve and response.

Great. I'll leave this issue open until I can provide a solution to https://github.com/conda-forge/lfpy-feedstock/issues/24

**Comment by espenhgn** [comment]
Closing this (for now). Creating new environments as `conda create -n lfpytest python=3.9 pip lfpy` installs compatible builds of NEURON and LFPy (tested on OSX-64 and Ubuntu). If anyone sees a similar issue, make sure to keep packages up to date (`conda update --all` in environment), and if all fails, request a newer version of NEURON as `conda install neuron>='7.8.2 mpi_*_2'`.
