### ISSUE TITLE
Is the `recextelectrode.data` computed at run time?

### ISSUE THREAD

**Issue by alejoe91** [LFPy/LFPy#326]
Hi @espenhgn 

I'm refractoring MEArec to use the latest LFPy :)

Quick question: I pre-compute the transmembrane currents, then move and rotate the cell model and compute the LFP. I used to use `calc_lfp()`. Can I now just use `recexteelctrode.data`? Will the changes in the cell position and rotation triggere a new computation?

Thanks!

**Comment by espenhgn** [comment]
Hi @alejoe91, 
That sounds good! 
Yes, in general `<lfpykit.models.*>` instance's `data` attribute should be set at run time if the `LFPy.Cell.simulate()` method receives a list `probes=[<lfpykit.models.*>, ...]`. So the `data` attribute is here the predicted signal - not the mapping or anything. 

In case transmembrane currents are pre-computed, the following procedure should apply: 
```
predictor = lfpykit.models.<ClassName>(cell=cell, **kwargs)
data = predictor.get_transformation_matrix() @ cell.imem
```
In case you alter the cell geometry just make sure to update the lfpykit class instance accordingly (`predictor.cell = anothercell`) before calling the `get_transformation_matrix()` method.

**Comment by espenhgn** [comment]
btw., are any refactoring of MEArec itself needed at all for LFPy? I've been using the current version without issues that I noticed. It is now only imported by LFPykit and only indirectly by LFPy, so we need to be a bit careful to not introduce some circular dependencies ;-)

**Comment by alejoe91** [comment]
Thanks Espen! Yes it does need some refractoring as the `calc_lfp` method is not there anymore :) I'll try your solution!

**Comment by espenhgn** [comment]
Good - btw., I again confused MEArec with MEAutility. LFPykit utilize the latter, hehe.

**Comment by espenhgn** [comment]
Think this can be closed.
