### ISSUE TITLE
How can I record the stimulation current of a StimIntElectrode

### ISSUE THREAD

**Issue by alejoe91** [LFPy/LFPy#330]
Hi @espenhgn 

What is the recommended way in the new API to record and retrieve the stimulation current from a point process?

Thanks in advance! :)

**Comment by espenhgn** [comment]
Bueno sera, @alejoe91. 
Do you mean target voltages/ stimulation currents? If so setting 
```
    record_current: bool
        Must be set to True for recording of pointprocess currents
    record_potential: bool
        Must be set to True for recording potential of pointprocess target idx
```
of the synapse/pointprocess when instantiating them should do the trick.

**Comment by alejoe91** [comment]
Buonasera a te! Exactly what I needed! Thank you :)

**Comment by alejoe91** [comment]
Actually Espen, can I retrieve it directly from the `Cell` object? I see there is a `self.synapses`, but can't find a `self.stims`...This would be more convenient for us :)

**Comment by alejoe91** [comment]
Mmm I think I found it: `cell.pointprocesses[idx].i` should do the trick right?

**Comment by espenhgn** [comment]
Yes, that should do it I assume.
