### ISSUE TITLE
Recording from individual electrode in electrode grid

### ISSUE THREAD

**Issue by RichaS19** [LFPy/LFPy#331]
Hello,

I've been trying to record field potential at different sites (dendritic area of neuron) and have been changing the electrode grid position, I wanted to ask if I can record field potential for all of them at once. Since I'm using a 7X7X7 grid i want to get field position for all of them but im unable to do that, could you please be able to help?

Also, would you suggest usage of MEA for that? if yes, I've been trying to record using that as well by using help from your example .py file and other sources. Could you please be able to guide me for this?

Thank you in advance!

Regards,
Richa

**Comment by espenhgn** [comment]
Hi @RichaS19; 
Yes, you should be able to predict the potential on an arbitrary spatial grid by first flattening the coordinate matrices; make the prediction, and reshape the output, see for instance block 7 and below in https://github.com/LFPy/LFPy/blob/master/examples/LFPy-example-03.ipynb. Pay attention to the `grid_electrode*` objects. 

The `RecMEAElectrode` class (https://lfpy.readthedocs.io/en/latest/classes.html#class-recmeaelectrode) is more tailored for accounting for different electric conductivities in different layers. For a 3D volumetric grid I think you probably want the usual assumption of infinite, homogeneous and anisotropic electric conductivity of `RecExtElectrode`.

**Comment by RichaS19** [comment]
I see. Thanks a lot! 

So , just one last clarification- If i have 7X7X7 (343) electrodes and i want to get field potential of all of them- like here : https://github.com/LFPy/LFPy/blob/master/examples/LFPy-example-04.ipynb in this example ; the LFPs of each electrode is shown in plot with the neuron morphology . 
1) how can I get their values by providing or specifying the coordinates/ that particular number of electrodes?
2) Another thing, when I'm giving flattened X,Y,Z in grid electrodes- it still isn't overlapping with the actual location in space (on only neuron dendrites lets say). I had gotten these coordinates from neuron compartments coordinates and while plotting here it overlaps with the entire neuron, and not just with the actual coordinate (that is, on dendrites) - Is that a plotting issue or the electrodes aren't on dendrites as specified with X,Y,Z coordinates in parameters?

Thank you in advance.

Regards,
Richa

**Comment by RichaS19** [comment]
In the example that you mentioned (example 3 ) in block 8 ; this line :- plt.plot(cell.tvec,**point_electrode.LFP[1]***1e6,color=color_vec[1], clip_on=False)

why grid_electrode can't be written, and what does this value in .LFP[ **value**] signifies ? 

Sorry for too many doubts; I just wanted to know how to get the field potentials of each electrode in my grid and how to specify their position here so as to get the plot for specific electrode/grid?

Thanks

**Comment by espenhgn** [comment]
Hi again, 
If I understand you correctly, something like this would allow you to extract time series in certain coordinates:
```
import numpy as np
x=y=z=np.arange(7)
X,Y,Z=np.meshgrid(x,y,z) # coordinate mesh (to be flattened)
...
data = np.random.randn(X.size, 100) # mock up whatever M @ cell.imem would produce for 100 simulated time steps
data = data.reshape(X.shape + (data.shape[-1], )) # shape (343, 100) -> (7, 7, 7, 100) 
data[x==0, y==1, z==2, :] # 1D time series at location (0, 1, 2)
```

If you would rather compute the potential at each compartment's midpoint you could define coordinates as `x = cell.x.mean(axis=-1)` and so forth.

**Comment by espenhgn** [comment]
Btw, if you are not familiar with numpy array indexing; see for instance https://numpy.org/devdocs/user/basics.indexing.html

**Comment by RichaS19** [comment]
Hello,

Thanks for your quick response.

I did not get it. I wanted the field potentials (for whole tstop) at each electrode. Like in example 4 : only for one location, the field potentials were plotted.I f I am giving X, Y, Z coordinates for electrode positions, how can i get field potentials plotted for each one of them. 
- specifically asking how can i get extracellular spike (the plot and recording) of each electrode. I mean, where do I specify the electrode x,y,z position in order to get field potential for that electrode?

**Comment by RichaS19** [comment]
Also, if you see in this figure- I had specified the electrodes X,Y and Z which should be on basal side and soma but it is spanning the entire neuron. is it because neuron's coordinates are different in this space?

**Comment by espenhgn** [comment]
Hi. I think it remains quite unclear what you are actually asking (I get that your first language is not English, but it is somewhat hard to decipher). 

The parameters `x,y,z` to class `RecExtElectrode` (https://lfpy.readthedocs.io/en/v2.2.1/classes.html#class-recextelectrode) should be 1D arrays of equal length, describing the coordinates at which the extracellular potential will be computed. If you create your ND coordinate arrays using `np.meshgrid` or similar the corresponding arrays must be flattened to 1D.

Then, there are two ways to compute these potentials in LFPy:

1. Precompute transmembrane currents for all compartments (`cell.simulate(rec_imem=True)` resulting in `cell.imem`), compute a linear map of said currents in all electrode coordinates (using `M = <RecExtElectrode object>.get_transformation_matrix()`) and multiply as `data = M @ cell.imem` as in https://github.com/LFPy/LFPy/blob/master/examples/LFPy-example-03.ipynb. This works as `cell.imem.shape` is `(n_segments, n_timesteps)` and `M.shape` is `(n_contacts, n_segments)`, as the operation `M @ cell.imem` is the same as `np.matmul(M, cell.imem)`. The output shape is always `(n_contacts, n_timesteps)`
2. Let LFPy compute the extracellular signal without recording transmembrane currents as in https://github.com/LFPy/LFPy/blob/master/examples/LFPy-example-04.ipynb:
    ```
    electrode = LFPy.RecExtElectrode(cell=cell, **electrodeParameters)
    cell.simulate(probes=[electrode])
    ```
     Then `electrode.data` will contain your extracellular potentials in an array of shape `(n_contacts, n_timesteps)` as above. 

If your use case warrants it, you can reshape the now 2D `(n_contacts, n_timesteps)` data array to match the ND grid of electrode contact points, but keep in mind the last axis which now describes the temporal dimension in this `(dim_1, dim_2, ..., dim_N, n_timesteps)` shaped array. If you want to access the values contained within you have to index as you would any other numpy array.

Finally, try and understand what is going on using the `LineCollection` class inside the function `plotstuff` in LFPy-example-04.ipynb. That's the part that creates the coloured traces shown in specific locations in panel a.

**Comment by RichaS19** [comment]
Dear Sir,

I do not think I muddled up the language, still I am sorry if I couldn’t convey my question/confusion to you.

I understand how to compute the extracellular potential. And I understand how it’s been used in example 3 and 4. All I wanted to ask was how and where to give command for one specific electrode position (i.e., xyz coordinate of that particular electrode) in order to get the plot/recording of extracellular potential from that electrode.

It’s okay, I’ll try to figure out.
Thank you so much for you help.

Regards,
Richa

**Comment by espenhgn** [comment]
Hi again, Richa.
> Dear Sir,
> 
> I do not think I muddled up the language, still I am sorry if I couldn’t convey my question/confusion to you.

I'm really sorry if I came across as unnecessary brash! No offence intended.  
> 
> I understand how to compute the extracellular potential. And I understand how it’s been used in example 3 and 4. All I wanted to ask was how and where to give command for one specific electrode position (i.e., xyz coordinate of that particular electrode) in order to get the plot/recording of extracellular potential from that electrode.

Ok, that was easier to understand. There is no such command, as the locations of the predicted signals should already be well defined by the `x,y,z`-parameters/arrays passed to class `RecExtElectrode` when you create the object `electrode` (or similar). You can try and create a boolean index array `index = (x==0) & (y==1) & (z==2)` (just substitute those numbers by whatever you like but they must exist on the grid described by `x,y,z` - otherwise all entries in `index` will be `False`). Then you can slice through all contacts as `data_at_index = electrode.data[index, :]`. Hope that clears things up enough. 
 
> 
> It’s okay, I’ll try to figure out.
> Thank you so much for you help.
> 
> Regards,
> Richa

Hope you figure it out. And also don't hesitate to contact us again if you encounter more trouble. 

Best,
Espen.

**Comment by RichaS19** [comment]
Sure Sir. I understand it now. Thank you!

Also, I've been using the `electrode.calc_lfp() ` so far but on your suggestion in point 1, and while observing the example again I saw that instead of that - electrode.get_transformation_matrix() is used.
However, it threw me an attribute error :-`AttributeError: 'RecExtElectrode' object has no attribute 'get_transformation_matrix'`
Have you updated this part in recextelectrode.py file recently? As, I've downloaded it long back and have been using those files ever since. Or am I doing something wrong?

Thank you in advance.

**Comment by espenhgn** [comment]
Yes, indeed, we have changed things a bit in the latest versions of LFPy, also in ways that are not completely backwards compatible with version v2.1.* and earlier as summarized here: https://github.com/LFPy/LFPy/releases/tag/v2.2. 

The latest version is v2.2.1 (https://github.com/LFPy/LFPy/releases/tag/v2.2.1). 

You can check what version you have as `LFPy.__version__`. Unless you update, you should match the code examples/documentation you look at with the corresponding version (using git tags for instance: https://github.com/LFPy/LFPy/tags)

**Comment by RichaS19** [comment]
Okay, sure. 
Thank you so much!
