### ISSUE TITLE
Query regarding actual coordinates of neuron

### ISSUE THREAD

**Issue by RichaS19** [LFPy/LFPy#338]
Hello,

This is regarding a simple doubt I had while running my files-

I am calling morphology of a neuron as .hoc file (with all pt3d coordinates accounting for morphologically realistic neuron) in my python file. In that python file, I am specifying this neuron as cell and later, giving specific coordinates for electrodes.
I just wanted to clarify:- The exact coordinates specified in that hoc file for neuron remains same while using in python file, right? 
To be more specific :- In the examples files (say, example 2 or 3) that you have provided on site, is it altering neuron's coordinates/position by any way? It is adjusted while setting the rotation and position [ cell.set_pos(x=-10, y=0, z=0) OR cell.set_rotation(z=np.pi) ] ; But it is not changing the actual coordinates of neuron that are specified in the morphology file, am I right?

Overall, I just wanted to confirm that the actual coordinates of neuron is intact throughout, and while changing cell.set_position and cell.set_rotation - we are just changing its position in space/plot ?

Thank you in advance.

Regards,
Richa

**Comment by RichaS19** [comment]
I am giving **coordinates of centroid of soma as x, y, z**  in `cell.set_pos(x,y,z)`
So, the entire neuron is actually set as it is right? with its original coordinates as given by pt3d coordinates? Or will it change it to set other way?

**Comment by espenhgn** [comment]
Hi Richa, 

There is a `pt3d=False/True` argument you can use with `LFPy.Cell`. If `True` the pt3d data points should also be updated in the NEURON namespace when creating the `Cell` object and if `cell.set_pos()` and similar is used. If `False` (default) the pt3d info should be unaffected, even if `cell.set_pos()` is called later on.

The center of the root segment will be put in position x, y, z by `cell.set_pos(x, y, z)`. By default this position is x=y=z=0 when creating cells.

**Comment by RichaS19** [comment]
So, pt3d should be set to false if I want the original coordinates to be unaffected throughout, right? And then, I do not need to set position or rotation?!

**Comment by espenhgn** [comment]
With `pt3d=False`, `Cell.set_rotation()` and `Cell.set_pos()` should only affect the coordinates of the `Cell` object, specifically its attributes `x`, `y` and `z` since LFPy>=2.2. These will obviously affect forward-model predictions.

**Comment by RichaS19** [comment]
Okay.
Thank you so much!

**Comment by espenhgn** [comment]
No problem!
