### ISSUE TITLE
Query regarding working of LFPy with NEURON 

### ISSUE THREAD

**Issue by RichaS19** [LFPy/LFPy#340]
Hello,

I have encountered one issue- i'm giving some time varying input in my hoc file- which is then called in python code where I'm recording LFPs. 
But since, those input are changing as a function of time, its working separately from NEURON gui, but with the LFPy code it shows no current; hence no field potential.

Could you please be able to suggest where can we introduce this time varying factor so that one can record extracellular potentials along with those events at that particular time.

Thank you in advance.

Kind regards,
Richa

**Comment by espenhgn** [comment]
Hi, 
I can't tell what this hoc code file you are using is supposed to be doing, exactly. Can you post the relevant code excerpts?

LFPy already provides the `Synapse` and `StimIntElectrode` classes which wraps around different point processes that are provided with NEURON for event-activated synapse types and electrode currents respectively, but nothing that I know prevents use of NEURON's `h.Vector.play()` method either:
![image](https://user-images.githubusercontent.com/2492641/124660965-30872500-dea7-11eb-9404-4fae0f62b55c.png)

**Comment by RichaS19** [comment]
It is sorted now, thank you.
