### ISSUE TITLE
How to retrieve RecExtElectrode data in the parallel simulation of the network model?

### ISSUE THREAD

**Issue by acyang** [LFPy/LFPy#341]
I'm using NEURON7.8.2+LFPy2.2.1 to simulate a small network model and to record LFP via RecExtElectrode class in LFPy.
I modified the example_network.py locates in LFPy/examples/example_network/ folder.
I ran my simulation with two cores and I want to retrieve RecExtElectrode data from every MPI rank.
```
    # set up extracellular recording device.
    # Here `cell` is set to None as handles to cell geometry is handled
    # internally
    electrode = RecExtElectrode(cell=None, **electrodeParameters)
 
   # reduce electrode
    if RANK == 0:
        print("rank: {}".format(RANK), electrode.data)
        #M = electrode.get_transformation_matrix()
    else:
        print("rank: {}".format(RANK), electrode.data)
        #M = electrode.get_transformation_matrix()
```
But only RecExtElectrode object in Rank0 is valid.
```
rank: 1 None
rank: 0 [[(-4.19529997e-07, -3.34924876e-07, -8.46051213e-08)...
```

I also tried to use get_transformation_matrix() and V=M@cell.imem
But it raises AttributeError because I set cell=None in the electrode setup.

It is possible to do such simulation via NEURON and LFPy?
Or how do I setup simulation correctly?
Any suggestions are big big welcome.
Thanks.

**Comment by espenhgn** [comment]
Hi @acyang, 
Right now it is not possible to store the output per MPI process, as the `Network.simulate` method performs some summing (calling `MPI::Reduce`) automatically if you use the procedure here: https://github.com/LFPy/LFPy/blob/6a6d7d38febbb4bf871b007e683589ba4db0168a/examples/example_network/example_network.py#L302

You could comment out this clause though to avoid the summing operation I believe: https://github.com/LFPy/LFPy/blob/6a6d7d38febbb4bf871b007e683589ba4db0168a/LFPy/network.py#L1136

**Comment by espenhgn** [comment]
Closing this. @acyang, please let me know if you have any remaining questions.
