### ISSUE TITLE
Error Loading Blue Brain Project Models

### ISSUE THREAD

**Issue by ZiadAli** [LFPy/LFPy#342]
Hello,

I'm attempting to load a Blue Brain neuron model into LFPy but I've been encountering some errors. When I run the code below I get the following error. This error shows up even when I comment out "forall delete_section()" in the template.hoc file, so I'm not sure how to interpret it. I've attached the folder with the cell files in it and it can also be downloaded from https://bbp.epfl.ch/nmc-portal/downloads.html.
[BlueBrain-cADpyr231_1.zip](https://github.com/LFPy/LFPy/files/7102493/BlueBrain-cADpyr231_1.zip)
 If anybody has any ideas I'd appreciate it - thanks! --Ziad

CODE:
```
cellParameters = {
    'morphology'    : 'BlueBrain-cADpyr231_1/morphology/dend-C301101A1_axon-tkb070125a3_ch1_cc2_b_hw_60x_1_-_Clone_4.asc',
    'templatefile'  : 'BlueBrain-cADpyr231_1/template.hoc',
    'templatename'  : 'cADpyr231_L6_TPC_L1_68efb03f39',
    'templateargs'  : 'BlueBrain-cADpyr231_1/morphology/dend-C301101A1_axon-tkb070125a3_ch1_cc2_b_hw_60x_1_-_Clone_4.asc',
    'passive' : False,
    'nsegs_method' : None,
    'dt' : 2**-5,
    'tstart' : -159,
    'tstop' : 10,
    'v_init' : -60,
    'celsius': 34,
    'pt3d' : True,
}
os.system('''
          cd BlueBrain-cADpyr231_1/mechanisms/
          nrnivmodl
          ''')
neuron.load_mechanisms('BlueBrain-cADpyr231_1/mechanisms/')

cell = LFPy.TemplateCell(**cellParameters)
```

ERROR:
```
`NEURON: interpreter stack type error
 near line 0
 forall delete_section()
                        ^
        cADpyr231_L6_TPC_L1_68efb03f39[0].init("BlueBrain-...")
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-5-f4a7563e67e8> in <module>
      1 #LFPy.cell.neuron.h("forall delete_section()")
----> 2 cell = LFPy.TemplateCell(**cellParameters)

/anaconda3/lib/python3.6/site-packages/LFPy/templatecell.py in __init__(self, templatefile, templatename, templateargs, verbose, **kwargs)
    146 
    147         # initialize the parent Cell object
--> 148         super().__init__(**kwargs)
    149 
    150     def _load_geometry(self):

/anaconda3/lib/python3.6/site-packages/LFPy/cell.py in __init__(self, morphology, v_init, Ra, cm, passive, passive_parameters, extracellular, tstart, tstop, dt, nsegs_method, lambda_f, d_lambda, max_nsegs_length, delete_sections, custom_code, custom_fun, custom_fun_args, pt3d, celsius, verbose, **kwargs)
    190         if isinstance(self.morphology, str):
    191             if os.path.isfile(self.morphology):
--> 192                 self._load_geometry()
    193             else:
    194                 raise Exception('non-existent file %s' % self.morphology)

/anaconda3/lib/python3.6/site-packages/LFPy/templatecell.py in _load_geometry(self)
    151         """Load the morphology-file in NEURON"""
    152         # the python cell object we are loading the morphology into:
--> 153         self.template = getattr(neuron.h, self.templatename)(self.templateargs)
    154 
    155         # perform a test if the morphology is already loaded:

RuntimeError: hoc error`
```

**Comment by torbjone** [comment]
Hi Ziad,
as I remember, we had some issues with running these models straight from the box, but I don't remember the exact problem. Have you looked at this example file?:
https://github.com/LFPy/LFPy/blob/master/examples/example_EPFL_neurons.py
It shows an example of how these cell models can be used with LFPy, but it contains a bit more code.

**Comment by espenhgn** [comment]
Yes, the `example_EPFL_neurons.py` script should still work with cell models unzipped from https://bbp.epfl.ch/nmc-portal/assets/documents/static/Download/hoc_combos_syn.1_0_10.allzips.tar (just checked w. LFPy@master)

As far as I remember, the main trick was to change the working folder in order to load the template descriptions for each cell model followed by creating the `LFPy.TemplateCell` object itself.

**Comment by ZiadAli** [comment]
The EPFL_neurons.py example helped - I don't know what was wrong with my initial implementation still but this achieves the same thing so I will use it instead. Thanks!

**Comment by espenhgn** [comment]
Sounds good! Your problem was most likely due to the fact that the different model .hoc files must be executed from the folder they reside in, as they contain hardcoded relative paths like `load_file("morphology.hoc")` and similar. Closing this then.
