### ISSUE TITLE
define_shape causing weird artifacts when connection are not only on endpoints

### ISSUE THREAD

**Issue by alejoe91** [LFPy/LFPy#353]
**Describe the bug**
As per the [`define_shape`](https://www.neuron.yale.edu/neuron/static/py_doc/modelspec/programmatic/topology/geometry.html#define_shape) description, the function should not be run "when a branch is connected to the interior of a parent section 0 < x < 1".

This is causing weird artifacts on our side. In this example, the red morphology is the correct morphology (without `define_shape`), while the why is after loading it with LFPy. The left arbor is shifted toward the some, probably because the connection between the dendrite and the some happens at 0.5.

![image](https://user-images.githubusercontent.com/17097257/138907761-e31b1dd1-ae77-4186-96d0-ff375bfe1e86.png)

Strangely, this only happens when we rename some sections using a morphology modifier on the neuron sectionlist...

**To Reproduce**
I can provide a sample morphology if needed.

**Expected behavior**
The 3d points don't get affected by `define_shape` if intermediate connections are present

**Desktop/Environment (please complete the following information):**
 Tested on both mac and linux with latest release and master branch.

**Additional context**
Will make a proposal PR shortly!

**Comment by espenhgn** [comment]
Hi @alejoe91; thanks for looking into this and providing a fix. 
So what shall we consider a "correct" morphology? The reconstruction file itself; or the way NEURON interprets the file, with or without calling `define_shape()`? 

File interpretation is apparently ambiguous looking at https://docs.arbor-sim.org/en/latest/fileformat/swc.html for instance. 

As far as I recall we call the `define_shape` function in case some morphology has been defined in multiple steps such as loading soma + dendrites from file and attaching additional sections representing axons for example, without explicitly setting pt3d info but only attachment points (and make every section "snap" in place to close gaps). This method has been used in various models, Hay 2011 for instance.

**Comment by alejoe91** [comment]
Yeah it's a tricky one @espenhgn 

I have been thinking about it and maybe a possible solution could be, instead, to add an optional arg to the `Cell` constructor called `define_shape` (`True` by default). So if a user wants to skip this step (s)he can. What do you think?

**Comment by espenhgn** [comment]
Could it be the case that your morphology setup should use `h.pt3dstyle(1, x, y, z)`? Sounds like that should preserve relative locations when translating/rotating the geometry, see also this: https://github.com/neuronsimulator/nrn/issues/909#issuecomment-766420168

**Comment by alejoe91** [comment]
> Could it be the case that your morphology setup should use `h.pt3dstyle(1, x, y, z)`? Sounds like that should preserve relative locations when translating/rotating the geometry, see also this: [neuronsimulator/nrn#909 (comment)](https://github.com/neuronsimulator/nrn/issues/909#issuecomment-766420168)

It could be an option! Would you have time for a call in the next days? I'll send you an email!

**Comment by espenhgn** [comment]
Looks like `pt3dstyle(1, **args)` is the way to go:
![image](https://user-images.githubusercontent.com/2492641/139045782-e49dbd5f-fff2-4e69-b914-e08539da7896.png)

**Comment by alejoe91** [comment]
@espenhgn thank you so much for the suggestion!

I tried something around and it seems that just using `neuron.h.pt3dconst(1, sec=sec)` for all newly created sections fixes the issue and `define_shape` doesn't modify the 3d position :)

**Comment by espenhgn** [comment]
I'll reopen this issue rather than create a new one. If we can avoid `neuron.h.define_shape()` altogether or only call it when sections with no pt3d info is encountered it is probably for the better. 
Here's another example where the morphology information is distorted as `pt3dconst(1, **args)` or `pt3dstyle(1, **args)` is not explicitly called: 
![image](https://user-images.githubusercontent.com/2492641/139247314-c1c2affe-f8b0-4e42-a394-c8232f935f6a.png)

We should create a few additional tests also loading reconstructions on .swc or similar format. 
As a minimal measure, we should create some warnings that geometries of certain sections has been translated.
