### ISSUE TITLE
Building network issue

### ISSUE THREAD

**Issue by Alexis-Melot** [LFPy/LFPy#357]
Hello,

I have a similar issue to this one (https://github.com/LFPy/LFPy/issues/287#issue-760697487) that didn't explain the solution.

I'm running example_network.py (
The difference is that I'm running on win10, conda env with python3.9.7 and lfpy=2.2.2.

Here is my version of the error : 
-------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\alexi\Desktop\MEArec\lfpy_network.py", line 263, in <module>
    network.create_population(name=name, POP_SIZE=pop_size,
  File "C:\Users\alexi\anaconda3\envs\RC_Encoder\lib\site-packages\LFPy\network.py", line 612, in create_population
    self.pc.cell(gid, cell._hoc_sd_netconlist[-1])
IndexError: List[7]
-------------------------------------------------------------

I got this issue after changing 'delete_sections' to True which is the only modification I made to the code.

**Comment by torbjone** [comment]
Hi, and thank you for your interest in LFPy :-)
Is there any reason why you changed to 'delete_sections'=True? It should probably be false, since otherwise NEURON will try to delete all sections in memory, thereby destroying the network.

**Comment by Alexis-Melot** [comment]
I changed it because I got 636 warning message of this type : 

--------
C:\Users\alexi\anaconda3\envs\RC_Encoder\lib\site-packages\LFPy\cell.py:182: UserWarning: 636 sections detected! Consider setting 'delete_sections=True'
  warn(mssg)
------

and this Error : 
-------
Traceback (most recent call last):
  File "C:\Users\alexi\Desktop\MEArec\example_network.py", line 301, in <module>
    (conncount, syncount) = network.connect(
  File "C:\Users\alexi\anaconda3\envs\RC_Encoder\lib\site-packages\LFPy\network.py", line 799, in connect
    nidx = int(round(multapsefun(**multapseargs)))
TypeError: type rv_frozen doesn't define __round__ method
------

**Comment by espenhgn** [comment]
Hi @Alexis-Melot; 
The way we print a warning is a bit ham-fisted, but it should be ignored with networks. It's just for information that iterative creation of `LFPy.TemplateCell` or `LFPy.NetworkCell` objects may leave references to Section objects in the NEURON namespace even if after the python objects are gone. We should find a neater way I think. 

As for the 2nd error, this may have been introduced by using the `example_network.py` script from the current master and LFPy=2.2.2 from say PyPi. That version does not support setting the `multapsefun` equal to a scipy.stats.* type function/method. That was only recently added addressing this issue: https://github.com/LFPy/LFPy/issues/318

**Comment by Alexis-Melot** [comment]
Hi @espenhgn ,

So if I understood well if I switch to numpy.random*type function/method to initialize `multapsefun` it should work with my lfpy version, is that it ?

**Comment by espenhgn** [comment]
> Hi @espenhgn ,
> 
> So if I understood well if I switch to numpy.random*type function/method to initialize `multapsefun` it should work with my lfpy version, is that it ?

Yes, I believe so. Please check your file against https://raw.githubusercontent.com/LFPy/LFPy/v2.2.2/examples/example_network/example_network.py

**Comment by Alexis-Melot** [comment]
it works thank you

**Comment by espenhgn** [comment]
Great! I think this one can be closed then. Let us know if you encounter other issues.
