### ISSUE TITLE
`create_synapse` and `Synapse` have different behavior

### ISSUE THREAD

**Issue by arashgmn** [LFPy/LFPy#368]
`create_syanpse` method of `Network` class doesn't append the created synapses to the `cell.synapse` list. Yet, it correctly updates the `netconsynapses` for each `cell`. It causes confusion, especially while working with networks with populations receiving both internal and external synaptic inputs.

**Suggestion**
I suggest 
1. adding every synapse that is created by `create_synapse` to the `cell.synapses` list, and  
2. unifying the attributes and methods of synapse objects created by `Synapse` and `create_synapse`.

**Example of such difference**
In the [network example](https://github.com/LFPy/LFPy/blob/master/examples/example_network/example_network.py) file, for instance, the network has hundreds of synaptic connections among excitatory (E) and inhibitory (I) populations. In addition, each population takes 64 external inputs. But each `cell` in each population only sees the external synaptic connections:

```python
cell0 = network.population['I'].cells[0] # or any other cell
len(cell.synapses) # = 64 because only external are added to this list
```

**Comment by espenhgn** [comment]
Hi @arashgmn, 
Thanks for pointing this out. This is certainly something that should see some improvements in the future. 

As far as I recall I did not want to put synapses from recurrent connections (set up using the hoc class directly) and external synapses (usually instances of `LFPy.Synapse`) in the same lists as they are not similar objects. 

So to get the actual number of synapses one would for now have to concatenate the two lists issuing `len(cell.synapses + cell.netconsynapses)` or similar.
