### ISSUE TITLE
NotImplementedError for `Network.enable_extracellular_stimulation()`

### ISSUE THREAD

**Issue by Alexis-Melot** [LFPy/LFPy#372]
Hello !

**Describe the bug**
I want to use the method `enable_extracellular_stimulation()` for a `network` object but it seems it isn't implement in the last version of lfpy.
Are you planning on implementing it soon ? 
is there another way to stimulate a network with extracellular current ?

**Desktop/Environment (please complete the following information):**
 - OS: Ubuntu 20.04.3 LTS
 - Shell: bash
 - Python-Version: Python 3.8
 - LFPy version: 2.2.3
 - Installation: conda install

**Comment by espenhgn** [comment]
Hello @Alexis-Melot, 
I guess this feature, which indeed would be nice to have in LFPy, didn't have a particular use case so far. But it sounds like this is now the case :)
I won't be able to incorporate it immediately, but if you feel adventurous you could perhaps consider doing this yourself? I don't think the approach would differ considerably from what is already in the Cell class: https://github.com/LFPy/LFPy/blob/fc0a3b784621d27cffabe4b6bcc13724f338c1dd/LFPy/cell.py#L914

In case of networks, it ought to be possible to then iterate over all cells in each population of the network (via `Network.populations['popname'].cells[...]` and call the `NetworkCell.insert_v_ext()` method with the appropriate potentials and time points. 

Edit: It looks like one could also call the Cell' class `enable_extracellular_stimulation` method from the corresponding method in the Network class. I have not tested it though. 

If you do happen to incorporate that `Network.enable_extracellular_stimulation` method in a PR, I would of course be happy to merge it into LFPy.

**Comment by Alexis-Melot** [comment]
Okay that's what I thought when I saw the method is only implemented for `cell` objects.
I'd be happy to give it at try sure but I'm kind of a newby, what is the protocol for this kind of thing ?
I make the code work on my version of lfpy
fill in for a pull request 
add my modification to the code 
and then push the code 

is that it ?

**Comment by espenhgn** [comment]
Yes, that is more or less it. Just fork this repository, create a feature branch and modify accordingly (see e.g., https://github.com/LFPy/LFPy/blob/master/.github/CONTRIBUTING.md). When you are ready, you can create a PR which will automatically trigger some checks. If you get stuck let me know, and good luck :)
