### ISSUE TITLE
CNS*2022 satellite tutorial on LFPy

### ISSUE THREAD

**Issue by sanjayankur31** [LFPy/LFPy#423]
Hello,

The INCF/OCNS Software WG is organising a set of free online satellite tutorials ahead of CNS*2022 in the week of June 27--July 1.

I was wondering what you thought of doing a session on LFPy too?

You can see the currently planned sessions etc here:
https://github.com/OCNS/SoftwareWG/milestone/3

The announcement post is here:
https://ocns.github.io/SoftwareWG/pages/software-wg-satellite-tutorials-at-cns-2022.html

Thanks very much,

**Comment by espenhgn** [comment]
Hi @sanjayankur31, 
Sounds like a good idea. We'll discuss this a bit internally, and get back to you.

**Comment by espenhgn** [comment]
Hi again @sanjayankur31. Let's feature an LFPy tutorial for this event. All dates but July 1 are ok for me.

**Comment by sanjayankur31** [comment]
Sounds good. I've opened a tracker ticket on our repo now. We'll start working on a schedule etc. soon.

**Comment by sanjayankur31** [comment]
Dear @espenhgn : if the session was recorded, could you please share the link so I can add it to the web pages and also send it to the INCF for uploading to their training space?
