### ISSUE TITLE
Make `mpi4py` an optional dependency

### ISSUE THREAD

**Issue by alejoe91** [LFPy/LFPy#429]
Hi @espenhgn 

**Is your feature request related to a problem? Please describe.**
Would it be possible to make `mpi4py` an optuional requirement, since it's only used in the network simulations?
We are integrating LFPy as a possible backend for BluePyOpt, and it seems like an unnecessary dependency since we only use single neuron models. See https://github.com/BlueBrain/BluePyOpt/pull/385#issuecomment-1193726658

**Describe the solution you'd like**
Make `mpi4py` optional in `network.py`.

Something like:
```
try:
    from mpi4py import MPI
    HAVE_MPI = True
except ImportError:
    HAVE_MPI = False
```

and then `asser HAVE_MPI` in the function and condinionally define the `def ReduceStructArray(sendbuf, op=MPI.SUM)` function:
```
if HAVE_MPI:
    def ReduceStructArray(sendbuf, op=MPI.SUM):
        ....
```

**Describe alternatives you've considered**
Making `mpi4py` a weak dependency with lazy import. You could also have a specific extra_requires `mpi4py`: `pip install LFPy[mpi]`

Let us know what you think!

**Comment by torbjone** [comment]
I am in favor of this. Also for some beginners (often on Windows machines), MPI can be a bit complicated.

**Comment by espenhgn** [comment]
Hi. I think whether or not MPI should be expected should perhaps be dealt with properly by BluePyOpt. Not having looked at how this package spawns tasks, one key issue is whether or not NEURON is MPI aware or not (by order of imports). I think mostly everyone now uses a NEURON version with MPI bindings (via pip, conda, or binary installers). Simply checking whether or not mpi4py is installed at runtime will not do, as the user may have this installed independently of LFPy already, hence using LFPy via BluePyOpt may result in unpredictable results. There are also `COMM.*` calls outside of the `ReduceStructArray` function throughout class `Network` which has to be dealt with.

I think the better solution to this problem of having mpi4py as a backend (never thought this was such a hurdle to install on the platforms we support properly), would be to replace our use of `mpi4py` functions (`Reduce` etc.) with the corresponding MPI wrapper functions provided via NEURON's `ParallelContext`: https://nrn.readthedocs.io/en/latest/python/modelspec/programmatic/network/parcon.html

As for LFPy Windows support, I think the only "official" support for LFPy remains via *nix Docker containers and similar as long as there is no pip installable NEURON version for Windows. We also have to set up proper GitHub tests for Windows when that time comes.

**Comment by alejoe91** [comment]
Hi @espenhgn 

The COMM stuff is already dealt with by asserting that the user has mpi4py in the init. I agree that most users would have MPI installed, but I don't see why a user without Neuron+mpi installed should be forced to install mpi if the network simulations are not used. No?

**Comment by espenhgn** [comment]
Hi @alejoe91,
The core of this issue is whether or not we should use `mpi4py` at all. 
If we with relative ease can get rid of this dependency altogether by replacing `mpi4py.MPI.COMM_WORLD.allgather(*args)` calls by `neuron.h.ParallelContext.py_allgather(*args)` etc., we should. This is done by for instance NetPyne (https://github.com/suny-downstate-medical-center/netpyne/blob/594f70ba4b4ec20346bb98e5335f20f4415f7b2c/netpyne/sim/gather.py).

**Comment by alejoe91** [comment]
> Hi @alejoe91, The core of this issue is whether or not we should use `mpi4py` at all. If we with relative ease can get rid of this dependency altogether by replacing `mpi4py.MPI.COMM_WORLD.allgather(*args)` calls by `neuron.h.ParallelContext.py_allgather(*args)` etc., we should. This is done by for instance NetPyne (https://github.com/suny-downstate-medical-center/netpyne/blob/594f70ba4b4ec20346bb98e5335f20f4415f7b2c/netpyne/sim/gather.py).

Sounds good! Is this planned?

**Comment by espenhgn** [comment]
Hi, @alejoe91. I added *this* issue now as a task for future LFPy-2.3 (https://github.com/LFPy/LFPy/projects/2). I haven't yet tested NEURON's MPI wrappers, but it seems fairly equivalent to mpi4py's, see https://nrn.readthedocs.io/en/latest/python/modelspec/programmatic/network/parcon.html

Do you have time to investigate?

**Comment by alejoe91** [comment]
> Hi, @alejoe91. I added _this_ issue now as a task for future LFPy-2.3 (https://github.com/LFPy/LFPy/projects/2). I haven't yet tested NEURON's MPI wrappers, but it seems fairly equivalent to mpi4py's, see https://nrn.readthedocs.io/en/latest/python/modelspec/programmatic/network/parcon.html
> 

Thanks Espen!

> Do you have time to investigate?

Unfortunately not, so I guess that for now we'll install from the branch I made the PR for until this is implemented.

**Comment by espenhgn** [comment]
> Unfortunately not, so I guess that for now we'll install from the branch I made the PR for until this is implemented.

Me neither, so this seems to be a good intermediate fix. I'll leave your PR hanging then :-)
