### ISSUE TITLE
NYHeadmodel on Docker: download by default?

### ISSUE THREAD

**Issue by filippomc** [LFPy/LFPy#444]
**Is your feature request related to a problem? Please describe.**
When using the Head model on Docker there is a prompt asking for downloading the model, which fails because of no input
device.

```
     79 
---> 80     nyhead = NYHeadModel()
     81 

/opt/conda/lib/python3.7/site-packages/lfpykit/eegmegcalc.py in __init__(self, nyhead_file)
   1390 
-> 1391         self._load_head_model(nyhead_file)
   1392 

/opt/conda/lib/python3.7/site-packages/lfpykit/eegmegcalc.py in _load_head_model(self, nyhead_file)
   1411             print("New York head-model file not found: %s" % self.head_file)
-> 1412             yn = input(f"Download as {self.head_file} (710 MB)? [y/n]: ")
   1413             if yn == 'y':

/opt/conda/lib/python3.7/site-packages/ipykernel/kernelbase.py in raw_input(self, prompt)
    845             raise StdinNotImplementedError(
--> 846                 "raw_input was called, but this frontend does not support input requests."
    847             )
StdinNotImplementedError: raw_input was called, but this frontend does not support input requests.
```

It would be nice to have it downloaded automatically instead.

**Describe the solution you'd like**
It would be nice that a check is done for the input to be available the file is download automatically.

**Describe alternatives you've considered**
We are now packing the file directly in the docker file, but that increases the size of the image and the head model is not always needed.

**Comment by torbjone** [comment]
Thank you for submitting this issue, I had not considered this. 

Do you think it would be a sufficient fix to change this to:

try:
    yn = input(f"Download as {self.head_file} (710 MB)? [y/n]: ")
except StdinNotImplementedError:
    yn = 'y'

Best regards,
Torbjørn

**Comment by filippomc** [comment]
Yes that would be perfect!

Thanks
Filippo

**Comment by torbjone** [comment]
The suggested change had been merged into the main branch of LFPykit, so if you rely on the source code from the github repository, this can be pulled in. But I guess you might be installing LFPy with pip? If so, I guess this change will not  take affect before we make a new release, and I will get back to you regarding this.

**Comment by filippomc** [comment]
Thanks, would really appreciate to know when this is included in the pip release.

**Comment by espenhgn** [comment]
Hi @filippomc; 
We'll provide a fix in [LFPykit](https://github.com/LFPy/LFPykit) for this issue, and publish a new release of that package shortly.

**Comment by espenhgn** [comment]
Hi @filippomc; [LFPykit-0.5.1](https://github.com/LFPy/LFPykit/releases/tag/v0.5.1) is now available across the usual channels (`pip install`, `conda install`). Can you test it? 

The main change is the removal of the `input()` prompt causing issues with the iPython frontend.

**Comment by filippomc** [comment]
Hi @espenhgn thanks I tested it and works for me
