### ISSUE TITLE
Add method to calculate membrane currents from membrane potentials

### ISSUE THREAD

**Issue by torbjone** [LFPy/LFPy#445]
In a project I'm working on, we have the membrane potentials (pre-simulated, loaded from file) of all compartments of a cell, but we need the membrane currents, and rerunning the simulations is not an option.

I have implemented a method that, as far as I have been able to test, always exactly reproduced 'cell.imem' directly from 'cell.vmem', given full knowledge of the cell model:

M = cell.get_transformation_matrix_vmem_to_imem()
imem = M @ cell.vmem

I have added some simple tests, including all relevant examples used to test 'get_axial_currents_from_vmem'. I have also tested that it works for more advanced cases, like the Hay model.

I suggest adding this method to LFPy, as it might also be useful for other cases. Any objections?

**Comment by espenhgn** [comment]
> Any objections?

Nope!
