### ISSUE TITLE
Question for 'Example 10: Extracellular stimulation of neurons' function

### ISSUE THREAD

**Issue by Vince0226** [LFPy/LFPy#462]
I have some questions for the following code in Example 10.
![image](https://github.com/user-attachments/assets/f6a3045f-e917-4953-a8c7-04856bca2fba)
Why do we use the function RecExtElectrode() to create LFPy electrode object to do extracellular stimulation rather than using StimIntElectrode()?

**Comment by espenhgn** [comment]
Hi @Vince0226,
The [StimIntElectrode](https://lfpy.readthedocs.io/en/latest/classes.html#class-stimintelectrode) represent intracellular electrode devices (patch electrodes), while [RecExtElectrode](https://lfpy.readthedocs.io/en/latest/classes.html#class-recextelectrode) represent extracellular recording devices. So the above example is representing the scenario where the potential outside the cell is changed via extracellular current stimulation, in contrast to feeding current into the intracellular volume.

**Comment by Vince0226** [comment]
I see. Thanks for your help.

**Comment by acyang** [comment]
Extending on this question, in example 10, it mentions enabling extracellular stimulation using the RecExtElectrode object. However, according to the manual, RecExtElectrode is a recording electrode. Is it appropriate to use it for delivering current pulses?

**Comment by espenhgn** [comment]
It's a matter of the way the class was implemented; initially as a recording device, but as the codebase/electrostatic forward models are shared it made sense to combine it in order to compute the outside potentials across the neuron. However, also real extracellular recording electrodes may be used for stimulation.
