### ISSUE TITLE
Windows build, examples and test suite

### ISSUE THREAD

**Issue by espenhgn** [LFPy/LFPy#57]
The Windows install procedure is a bit involved. Most tests fail because NEURON cannot deal with Windows style paths (as produced by `os.path.join`). Examples are also failing. 

Windows 10 Pro install instructions
- Download and install Anaconda Python from https://www.anaconda.com/download/ 
- Download and install NEURON from https://www.neuron.yale.edu/neuron/download. 
  Tick the box to "Set DOS environment" (Otherwise Anaconda Python will not find the NEURON python module)
- Download and install the Visual Studio C++ Build Tools 2015 from: http://landinghub.visualstudio.com/visual-cpp-build-tools
Choose the Visual C++ 2015 Build Tools option.
- Download and install Git from https://git-scm.com/downloads
- Download and install Microsoft MPI from the Official Microsoft Download Center: https://www.microsoft.com/en-us/download/details.aspx?id=55494
  Choose the file "MSMpiSetup.exe". 
- Open the Anaconda Prompt under the Anaconda* folder in the start menu
- Install additional LFPy dependencies using conda (to avoid package clashes with i.e., pip install)
    `conda install mpi4py`
- Clone into LFPy using Git:
    `git clone https://github.com/LFPy/LFPy.git`
- Build LFPy from source (without moving files)
    `python setup.py develop`
- NEURON NMODLfiles will not be autocompiled when building LFPy as on MacOS/Linux, 
  as the mknrndll script cannot be run directly in the Anaconda Prompt. To fix this, run the 
  "bash" file in the NEURON program group, change directory within "bash" to the `<LFPy>/LFPy/test` folder,  then run `mknrndll`

For the failing tests, it seems necessary in file paths passed on to `neuron.h.load_file` and similar functions to do a `str.replace(os.sep, "/")`

Several example files relying on `urllib` fail to download necessary files.

**Comment by espenhgn** [comment]
merged #58. Install instructions updated in branch `LFPy:docfix`. Closing.

**Comment by RichardGault22** [comment]
Hello,

I am having issues getting LFPy to work on Windows. In particular I am struggling with the final step outlined above:
"NEURON NMODLfiles will not be autocompiled when building LFPy as on MacOS/Linux,
as the mknrndll script cannot be run directly in the Anaconda Prompt. To fix this, run the
"bash" file in the NEURON program group, change directory within "bash" to the <LFPy>/LFPy/test folder, then run mknrndll"

I would be grateful if you could please elaborate on this point - I have found the "bash.exe" file within Neuron directory, I have been able to change directory to ...LFPy/LFPy/test but unsure how to run "mknrndll"?

**Comment by espenhgn** [comment]
Hi @RichardGault22 
Sorry you're having some problems. I don't know which exact version of NEURON and Windows you have, but on a Win 10 virtualbox w. NEURON 7.5 I have a 'bash' program under NEURON on the Start menu:
![image](https://user-images.githubusercontent.com/2492641/47658306-142d7900-db93-11e8-907b-0471346c058b.png)
That program provides a *nix style command line interface. Here change directory (`cd`) to `<LFPy>/LFPy/test` folder, then run `mknrndll` in order to make the LFPy unit tests run. You have to do this as well for examples/model codes that also rely on custom NMODL (`.mod`) files. 

I'm not using Windows usually, and couldn't find a neat way to automatize compilation of such files from say Python. Any help is therefore appreciated!

**Comment by RichardGault22** [comment]
Hi @espenhgn , 

Thank you for your quick response! I have located the bash file, I am able to change directory to LFPy/test 
![nrn_error](https://user-images.githubusercontent.com/25363903/47665804-e5ff6780-db99-11e8-961b-207da719ed1d.PNG)

When I try to run mknrndll (which might be the incorrect way) I get the error seen in the screenshot above. I would be very grateful for any advice you may have on how to progress with the LFPy installation.

**Comment by espenhgn** [comment]
Hi @RichardGault22 
Not sure what is going on. On my end I have no problems:
![image](https://user-images.githubusercontent.com/2492641/47680816-3c839a80-dbc8-11e8-9d72-ba18b16ee991.png)

If you get the same error in some other folder outside of the LFPy source tree, then I would conclude that your NEURON installation is somehow broken. In that case, I suggest posting on the NEURON forum at [neuron.yale.edu](neuron.yale.edu)
