### ISSUE TITLE
Using the TemplateCell object with biophysical models

### ISSUE THREAD

**Issue by tanselbaran** [LFPy/LFPy#83]
Hello, 

First of all, thanks so much for this useful resource! I had a few questions about using the TemplateCell object and using biophysically and anatomically detailed models such as the ones in modelDB with LFPy. I am relatively new to NEURON language, so my question may be very basic.

As far as I understood,  Cell object only allows definition of a morphology, but not the ion channel models. As I see from the example2, I'd have to use TemplateCell object for this, right? My question is, if I have only a morphology file and a .hoc file for the biophysics of the cell, what would have to go into the templatename? For all the models I used other than the one provided in the example, I get an AttributeError. 

For instance, I tried using the Layer 2/3 pyramidal neuron model from Traub et al 2003 at ModelDB in one of the examples. For the cellParameters argument of the TemplateCell object, I did the following: 

    'morphology'    : 'pyr3_template.hoc',
    'templatefile'  : 'pyr3_template.hoc',
    'templatename'  : 'pyr3_template',

Morphology and biophysics are both defined in this pyr3_template.hoc file. When I run the example, I get the following error: 
 AttributeError: 'hoc.HocObject' object has no attribute 'pyr3_template'

Alternatively, are you planning in the upcoming versions to add an argument like 'biophysics' to the Cell object, similar to how the 'morphology' is an argument? 

Thanks,
Baran Yasar

**Comment by espenhgn** [comment]
Hi @tanselbaran 

Thanks for your interest in LFPy!

I haven't tried to use the Traub model neurons myself with LFPy. The TemplateCell class was originally written to allow loading specific neuron models such as the Hay et al., 2011 pyramidal cell as demonstrated in the example file https://github.com/LFPy/LFPy/blob/master/examples/example_loadL5bPCmodelsEH.py

A simpler example is provided in https://github.com/LFPy/LFPy/blob/master/examples/example_LFPyCellTemplate.py and corresponding files

The main problem is that model specification in HOC is arbitrary (by for example defining everything in a single file, inside a function etc.), and if the Traub model files differ in their setup to the above examples, the TemplateCell class would likely fail. I think in your example, the template specification is not correctly loaded into the Neuron namespace, hence this AttributeError is raised. 

As for setting active channels through the Cell classes, one can do that by passing additional arguments:
```
custom_code : list or None
    list of model-specific code files ([.py/.hoc]). Defaults to None
custom_fun : list or None
    list of model-specific functions with args. Defaults to None
custom_fun_args : list or None
    list of args passed to custom_fun functions. Defaults to None
```

If you still cannot find a solution, don't hesitate to provide files to reproduce your error.

**Comment by espenhgn** [comment]
I should perhaps also clarify difference between Cell and TemplateCell. Templates in NEURON is basically how Neuron represents objects. The Cell loads everything, including section references, in its main namespace, hence only a single neuron can be created at the time. Templates allow section references to be attached to them, and several instances of a template can be created simultaneously. Hence multiple cells, and networks thereof, can be created in parallel.

**Comment by espenhgn** [comment]
Unless there's anything to add, I'm closing this issue for now.
