### ISSUE TITLE
RecMEAElectrode.test_cell_extent fix

### ISSUE THREAD

**Issue by espenhgn** [LFPy/LFPy#85]
Looks like this function should test not only the endpoint coordinates of the morphology vs. the upper and lower boundary, but also the start points. Maybe the method should also return the conflicting compartment # and morphology name in order to more easily identify which cell(s) may conflict with the geometry (for networks)

**Comment by torbjone** [comment]
Will not always the end points have both the highest and lowest values? 
Perhaps is can be a special case if the soma is the lowest compartment, I had not considered that possibility.

**Comment by espenhgn** [comment]
I suppose it would be possible to find a strange morphology where the start point is more extreme than the end point. 

My actual problem in some simulations I did was that some interneuron dendrite was conflicting with the lower boundary, while I thought it was the apical dendrite of an pyramidal neuron that caused problems with the upper boundary.

**Comment by torbjone** [comment]
Yes, that would of course require a discontinuous morphology, where there was a jump from the parent compartment end point to the child compartments start point, which then turned back, but I guess it is possible to make.

I will fix.

**Comment by torbjone** [comment]
PR has been made.

**Comment by espenhgn** [comment]
Merged #88 , closing issue.
