### ISSUE TITLE
compute dipole moments

### ISSUE THREAD

**Issue by YY535** [LFPy/LFPy#96]
Hello,
I'm a student quite new to NEURON and python environment. Currently, I'm trying to use some standard package to simulate a network with multicompartment neurons and end up choosing LFPy because it's quite nice organized and user friendly :-) There is one question I came across when I went through the scripts: 
it seems that you use two ways to compute dipole moments, in cell.simulation, it's i_membrane_ and distance of each compartment, while in network simulation you compute axial current from vmem and distance. Theoretically speaking (or only from the mathematical view of point?) they should give the same result, and l somehow have the impression that computing i_membrane_ should be faster? So why do you choose different methods?  Or maybe did I misunderstand something? 
Best
Weiwei

**Comment by espenhgn** [comment]
Hi @YY535 
Great that you find LFPy useful. 
With regards to your question, the Network class still uses the seg.i_membrane_ attribute to compute the current dipole moment as the product between the transmembrane currents and segment locations, see: https://github.com/LFPy/LFPy/blob/2f86fbd32bd5aa42f1df7100417c976c24699251/LFPy/network.py#L1448
Using axial currents or transmembrane currents to compute the dipole moment is indeed equivalent, but the entire procedure to first compute axial currents is more involved and we didn't implement this for networks.

**Comment by YY535** [comment]
Hi @espenhgn 
Thank you so much for the reply :-) And maybe one further question: basically for a population of neurons, line source approximation is not used to compute LFP or dipoles, right? Should not bring too much difference, right? 
Cheers

**Comment by espenhgn** [comment]
Hi, 
The LFP calculation can use point or line sources (as implemented in the RecExtElectrode class) for single cells or networks. The current dipole moment calculation uses point sources, as the difference in the extracellular potential between a line and point source diminish with distance.

**Comment by torbjone** [comment]
If I remember correctly, @solveignaess found that point sources and line sources actually gave identical results for the current dipole moment for all distances, not only far away, and therefore one might as well use the simpler point source in this case.

**Comment by solveignaess** [comment]
That's right! The results are identical for point source and line source when computing the current dipole moment. In case you're interested, the proof is given here: https://brage.bibsys.no/xmlui/handle/11250/292868 , section 2.3.2.?

________________________________
Fra: Torbjørn Vefferstad Ness <notifications@github.com>
Sendt: 30. april 2018 08:24
Til: LFPy/LFPy
Kopi: Solveig Næss; Mention
Emne: Re: [LFPy/LFPy] compute dipole moments (#96)


If I remember correctly, @solveignaess<https://github.com/solveignaess> found that point sources and line sources actually gave identical results for the current dipole moment for all distances, not only far away, and therefore one might as well use the simpler point source in this case.

-

**Comment by YY535** [comment]
Cool! Thank you all :-)
